#-------------------------------------------------------------------------------
# rex
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
# Initial configuration for testing
#-------------------------------------------------------------------------------

#FM350 modem
device {
  device_id: "pci:14c3:4d75 (External)"
  variant: "rex_fm350"
  default_main_firmware_version: "81600.0000.00.29.19.16"
  dlc {
    dlc_id:"modem-fw-dlc-rex-fm350"
  }

  main_firmware {
    filename: "fm350/81600.0000.00.29.19.16"
    version: "81600.0000.00.29.19.16"
    compression: NONE
    assoc_firmware {
      tag: "ap"
      filename: "fm350/FM350.C82"
      version: "FM350.C82"
      compression: NONE
    }
    assoc_firmware {
      tag: "dev"
      filename: "fm350/DEV_OTA_5001.0001.0000_Default_001.000.000.015.img"
      version: "5001.0001.0000_Default_001.000.000.015"
      compression: NONE
    }
  }

  oem_firmware {
    filename: "fm350/OEM_OTA_6001.0000.001.img"
    version: "6001.0000.001"
    main_firmware_version: "81600.0000.00.29.19.16"
    compression: NONE
  }

  carrier_firmware {
    filename: "fm350/OP_OTA_000.037.img"
    carrier_id: "generic"
    version: "000.037"
    compression: NONE
  }
}

#FM101 modem
device {
  device_id: "usb:2cb7:01a2"
  variant: "rex_fm101"
  default_main_firmware_version: "19500.0000.00.01.01.52"
  dlc {
    dlc_id: "modem-fw-dlc-rex-fm101"
  }
  main_firmware {
    filename: "fm101/19500.0000.00.01.01.52"
    version: "19500.0000.00.01.01.52"
    compression: NONE
    assoc_firmware {
      tag: "ap"
      filename: "fm101/A54"
      version: "A54"
      compression: NONE
    }
  }
  oem_firmware {
    filename: "fm101/OEM_OTA_6000.0000.004"
    version: "6000.0000.004"
    main_firmware_version: "19500.0000.00.01.01.52"
    compression: NONE
  }
  carrier_firmware {
    filename: "fm101/OP_OTA_000.019"
    carrier_id: "generic"
    version: "000.019"
    compression: NONE
  }
}
