helper {
  filename: "fm350-helper"
  device_id: "pci:14c3:4d75 (External)"
  variant: "rex_fm350"
}

helper {
  filename: "fm101-helper"
  device_id: "usb:2cb7:01a2"
  extra_argument: "--power_enable_gpio=INTC1083:00,111"
  variant: "rex_fm101"
}
