repo: "https://github.com/thesofproject/sof.git"
branch: "mt8186/v0.2"
commit: "714c6d4d8917684b4b1c44ebb61bc9483f915cfe"
tarball: "sof-topology-staryu"
version: "0.2.4"
topology: {
  docker: {
    use: true
    identifier: "gsoftools:latest"
  }
}
artifact: {
  name: "sof-mt8186.tplg"
  built_path: "tools/build_tools/topology/sof-mt8186.tplg"
  sha256: "4a10a6ef9620aab6ab9cbfed0a277c472ec62f358050983f5a9410aae4cd27c5"
}
