helper {
  filename: "l850gl-helper"
  device_id: "usb:2cb7:0007"
  extra_argument: "--power_enable_gpio=INTC1055:00,336"
  variant: "brya_l850"
  variant: "redrix_l850"
  variant: "anahera_l850"
  variant: "primus_l850"
}

helper {
  filename: "fm101-helper"
  device_id: "usb:2cb7:01a2"
  extra_argument: "--power_enable_gpio=INTC1055:00,84"
  variant: "crota_fm101"
}

helper {
  filename: "fm350-helper"
  device_id: "pci:14c3:4d75 (External)"
  extra_argument: "--power_enable_gpio=INTC1055:00,336"
  variant: "brya_fm350"
  variant: "bryati50_fm350"
  variant: "redrix_fm350"
  variant: "vell_fm350"
}
