#! /bin/sh

# Copyright 2021 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

case "$(tpm_version_client)" in
    0) echo "No TPM."
        ;;
    1) tpm1_version
        ;;
    2) tpm2_version
        ;;
    *) echo "Unknown TPM."
esac
