# Due to b/194944898 mount(8) does not accept LABEL= as a source.
# As a workaround, use blkid(8) to find the correct device path.
argv: "sh"
argv: "-c"
argv: 'mount -o ro "$(blkid -L cros-vm-tools)" /opt/google/cros-containers'
respawn: false
wait_for_exit: true
