#!/bin/bash
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# shellcheck source=common.sh
. "$(dirname "$0")/common.sh" || exit 1

new_script="update_chroot"
warn "$0: This script is deprecated and will be removed."
warn "All users must migrate to ${new_script} in chromite/bin."
warn "You can simply change all references of $0 to \`${new_script}\`" \
  "from \$PATH (in chromite/bin/)."
warn "This old script will be removed by June 2024."
warn "If you have questions or found code that needs updating, please" \
  "contact chromium-os-dev@, or file a bug at go/cros-build-bug."
exec "${CHROMITE_BIN}/${new_script}" "$@"
