helper {
  variant: "vilboz360"
  filename: "l850gl-helper"
  device_id: "usb:2cb7:0007"
  extra_argument: "--power_enable_gpio=AMD0030:00,89"
}
helper {
  variant: "vilboz"
  filename: "nl668am-helper"
  device_id: "usb:2cb7:01a0"
  extra_argument: "--power_enable_gpio=AMD0030:00,89"
}
