#!/bin/sh
# Copyright 2021 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Start ippusb_bridge through an upstart service instead of directly calling it
# here because udev will terminate all child processes once it finishes
# processing this event.  Once upstart starts the job, it will take care of
# restarting it until bridge_stop shuts it down during device removal.

logger -t bridge_start \
  "Starting ippusb_bridge for $ID_VENDOR_ID:$ID_MODEL_ID" \
  "on $BUSNUM:$DEVNUM ($DEVNAME)"
exec /sbin/start --quiet ippusb-bridge \
  BUS="$BUSNUM" DEV="$DEVNUM" VID="$ID_VENDOR_ID" PID="$ID_MODEL_ID"
