#!/bin/sh
#
# A script that handles /etc/init/autologin-wayneos.conf.
# Copyright (C) 2021 Wayne Inc. <seongbin@wayne-inc.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

print_usage(){
        echo "USAGE: $0 [flags]"
        echo "flags:"
        echo "  --status:       Check status of Autologin feature"
        echo "  --on:           Turn on Autologin feature (default)"
        echo "  --off:          Turn off Autologin feature (for powerwash/debugging)"
        echo "  --modify:       Modify the configuration file"
        echo "  --help:         Show this help"
}

conf_file_error() {
        echo "error: autologin-wayneos.conf* doesn't exist in /etc/init/"
}

if [ "$#" -ne 1 ]; then
        print_usage
        exit 1
fi

case "$1" in
        --status)
                if [ -f /etc/init/autologin-wayneos.conf ]; then
                        echo "Status: on"
                elif [ -f /etc/init/autologin-wayneos.conf.bak ]; then
                        echo "Status: off"
                else
                        conf_file_error
                fi
                exit 0
                ;;
        --on)
                if [ -f /etc/init/autologin-wayneos.conf ]; then
                        echo "Turned on already"
                        exit 0
                elif [ -f /etc/init/autologin-wayneos.conf.bak ]; then
                        sudo mount -o remount,rw /
                        sudo mv /etc/init/autologin-wayneos.conf.bak /etc/init/autologin-wayneos.conf
                        sudo mount -o remount,ro /
                        echo "Turned on"
                else
                        conf_file_error
                fi
                ;;
        --off)
                if [ -f /etc/init/autologin-wayneos.conf ]; then
                        sudo mount -o remount,rw /
                        sudo mv /etc/init/autologin-wayneos.conf /etc/init/autologin-wayneos.conf.bak
                        sudo mount -o remount,ro /
                        echo "Turned off"
                elif [ -f /etc/init/autologin-wayneos.conf.bak ]; then
                        echo "Turned off already"
                        exit 0
                else
                        conf_file_error
                fi
                ;;
        --modify)
                if [ -f /etc/init/autologin-wayneos.conf ]; then
                        sudo mount -o remount,rw /
                        # sudo vi /etc/init/autologin-wayneos.conf
                        sudo nano /etc/init/autologin-wayneos.conf
                        sudo mount -o remount,ro /
                        echo "Modified autologin-wayneos.conf"
                elif [ -f /etc/init/autologin-wayneos.conf.bak ]; then
                        sudo mount -o remount,rw /
                        # sudo vi /etc/init/autologin-wayneos.conf.bak
                        sudo nano /etc/init/autologin-wayneos.conf
                        sudo mount -o remount,ro /
                        echo "Modified autologin-wayneos.conf.bak"
                else
                        conf_file_error
                fi
                ;;
        --help|*)
                print_usage
                exit 1
                ;;
esac
echo "The change will show after reboot (sudo reboot)"
