# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

mno {
  data {
    uuid: "c83d6597-dc91-4d48-a3a7-d86b80123751"
    country: "us"
    localized_name {
      name: "Verizon Wireless - Hotspot"
    }
    olp {
      olp_filter {
        type: MCCMNC
        regex: "[0-9]+"
      }
      method: POST
      url: "https://quickaccess.verizonwireless.com/bbportal/chrome/start4g.do"
      post_data: "iccid=${iccid}&imei=${imei}&mdn=${mdn}"
    }
    mccmnc: "310995"
    mccmnc: "311270"
    mccmnc: "311480"
    tethering_allowed: true
    mobile_apn {
      apn: "vzwtether"
      is_required_by_carrier_spec: true
      ip_type: IPV4V6
      type: DEFAULT
      type: DUN
    }
  }
}

mno {
  data {
    uuid: "2951dc13-6c90-4200-b450-666efc95fa01"
    country: "us"
    localized_name {
      name: "T-Mobile - Hotspot"
    }
    mccmnc: "310026"
    mccmnc: "310160"
    mccmnc: "310200"
    mccmnc: "310210"
    mccmnc: "310220"
    mccmnc: "310230"
    mccmnc: "310240"
    mccmnc: "310250"
    mccmnc: "310260"
    mccmnc: "310270"
    mccmnc: "310310"
    mccmnc: "310490"
    mccmnc: "310580"
    mccmnc: "310660"
    mccmnc: "310800"
    mccmnc: "311882"
    mccmnc: "312250"
    tethering_allowed: true
    mobile_apn {
      # Tmobile requires a specific APN for GID1==544D
      apn_filter {
        type: GID1
        regex: "544D"
      }
      apn: "pcweb.tmobile.com"
      is_required_by_carrier_spec: true
      ip_type: IPV4V6
      type: DEFAULT
      type: DUN
    }
    mobile_apn {
      # Tmobile allows any APN for GID1!=544D
      apn_filter {
        type: GID1
        exclude_regex: "544D"
      }
      apn: "fast.t-mobile.com"
      ip_type: IPV4V6
      type: DEFAULT
      type: DUN
    }
  }
  # IoT Wholesale APN
  mvno {
    mvno_filter {
      type : IMSI
      range {
        start: 311882030000000
        end:   311882039999999
      }
      range {
        start: 310240200000000
        end:   310240209999999
      }
    }
    data {
      uuid : "ea77b4fc-befa-4cd7-980f-710c6c32a991"
      country : "us"
      localized_name {
        name : "T-Mobile"
      }
      mccmnc : "311882"
      mccmnc : "310240"
      tethering_allowed: true
      mobile_apn {
        apn : "iot.tmowholesale"
        localized_name {
          name : "IOT"
        }
        ip_type: IPV4V6
        type : DEFAULT
      }
    }
  }
}

mno {
  data {
    uuid: "f23f09a8-3416-4165-8654-25a59682af7a"
    country: "us"
    localized_name {
      name: "AT&T - Hotspot"
    }
    mccmnc: "310030"
    mccmnc: "310038"
    mccmnc: "310070"
    mccmnc: "310090"
    mccmnc: "310150"
    mccmnc: "310170"
    mccmnc: "310280"
    mccmnc: "310380"
    mccmnc: "310410"
    mccmnc: "310560"
    mccmnc: "310670"
    mccmnc: "310680"
    mccmnc: "310950"
    mccmnc: "310980"
    mccmnc: "311180"
    mccmnc: "312670"
    mccmnc: "313100"
    mccmnc: "313110"
    mccmnc: "313120"
    mccmnc: "313130"
    mccmnc: "313140"
    mccmnc: "313790"
    tethering_allowed: true
    mhs_entitlement_url: "http://entitlement.mobile.att.net/mhs1"
    mhs_entitlement_method: GET
    # Attach with broadband, but connect with hotspot
    mobile_apn {
      apn: "broadband"
      ip_type: IPV4V6
      type: IA
    }
    mobile_apn {
      apn: "hotspot"
      is_required_by_carrier_spec: true
      ip_type: IPV4V6
      type: DEFAULT
      type: DUN
    }
    mtu: 1430
  }
  mvno {
    mvno_filter {
      type: GID1
      regex: "53FF"
    }
    data {
      uuid: "a576607a-4958-11ed-b878-0242ac120002"
      country: "us"
      localized_name {
        name: "AT&T - Hotspot"
      }
      mccmnc: "310410"
      mccmnc: "310280"
      mccmnc: "311180"
      mccmnc: "310950"
      tethering_allowed: true
      mhs_entitlement_url: "http://entitlement.mobile.att.net/mhs1"
      mhs_entitlement_method: GET
      mobile_apn {
        apn: "nrbroadband"
        localized_name {
          name: "ATT NR Broadband"
        }
        ip_type: IPV4V6
        type: IA
      }
      mobile_apn {
        apn: "hotspot"
        is_required_by_carrier_spec: true
        ip_type: IPV4V6
        type: DEFAULT
        type: DUN
      }
      mtu: 1430
    }
  }
}

mno {
  data {
    uuid: "d433d22c-02ac-43b5-b2b3-91f96c4b2d7a"
    country: "zz"
    localized_name {
      name: "Test Network - Hotspot"
    }
    mccmnc: "00101"
    tethering_allowed: true
    mobile_apn {
      is_required_by_carrier_spec: true
      apn: "callbox-dun-ipv4v6"
      ip_type: IPV4V6
      type: DEFAULT
      type: IA
      type: DUN
    }
  }
}

mno {
  data {
    uuid : "29312b25-e5c7-47cc-b83c-32f9a10437d3"
    country : "es"
    localized_name {
      name : "Movistar (Telefónica) - Hotspot"
    }
    mccmnc : "21405"
    mccmnc : "21407"
    tethering_allowed: true
    mobile_apn {
      apn : "telefonica.es"
      localized_name {
        name : "Telefónica"
      }
      username : "telefonica"
      password : "telefonica"
      type : DEFAULT
      type : DUN
    }
  }
}

mno {
  data {
    uuid : "3c0341da-65f3-49f5-83c8-4d864b4e165e"
    country : "pl"
    localized_name {
      name : "Orange"
    }
    mccmnc : "26003"
    tethering_allowed: true
    mobile_apn {
      apn : "internet"
      localized_name {
        name : "Standard access - with image compression"
      }
      localized_name {
        name : "Dostęp standardowy - z kompresją grafiki"
      }
      username : "internet"
      password : "internet"
      type : DEFAULT
    }
  }
}
