#!/bin/bash
# Copyright 2018 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

main() {
  local target_dir=/mnt/stateful_partition/encrypted/var/cache/camera
  if [[ ! -d "${target_dir}" ]]; then
    rm -rf "${target_dir}"
    mkdir -p "${target_dir}"
  fi

  cp /etc/camera/media_profiles.xml "${target_dir}"
  return 0
}

main "$@"
