#!/bin/bash

# Copyright 2021 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

GPIO_ID=89
GPIO_OFFSET=$(cat /sys/devices/platform/AMD0030:00/gpio/gpiochip[0-9]*/base)
GPIO=$((GPIO_OFFSET + GPIO_ID))
GPIO_PATH="/sys/class/gpio/gpio${GPIO}/"

log() {
  logger "[modem]" "$@"
}

has_modem() {
  cros_config /modem firmware-variant > /dev/null
}

is_modem_ready() {
  ls /dev/serial/by-id/usb-Fibocom_Wireless_Inc.* > /dev/null 2>&1
}

has_modem || exit 0

if [[ -d ${GPIO_PATH} ]]; then
  log "de-assert GPIO ${GPIO}"
  echo 1 > "${GPIO_PATH}/value"
fi
