#!/bin/sh -u
# Copyright 2011 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Install Chrome/Chromium OS from the recovery installer.

if [ $# -lt 1 ]; then
  echo "usage:  $0 <source-device> [ ... extra flags for chromeos-install]" >&2
  exit 1
fi

# Prevent kernel key version roll forward until the system can read policy.
# After policy is available the update_engine will decide the correct value for
# kernel_max_rollforward.
crossystem kernel_max_rollforward=0

export IS_RECOVERY_INSTALL=1
src_device="$1"
shift
exec chromeos-install --storage_diags --yes --payload_image="${src_device}" "$@"
