# Copyright 2019 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Test[200] MobileOperatorInfoDataTest.*
# Test[200] MobileOperatorInfoObserverTest.*
mno {
  data {
    uuid: "uuid200001"
    country: "us"
    localized_name {
      name: "name200001"
      language: "en"
    }
    localized_name {
      name: "name200002"
    }
    requires_roaming: true
    tethering_allowed: true
    use_dun_apn_as_default: true
    mhs_entitlement_url: "uuid200001.com"
    mhs_entitlement_param: IMSI
    mhs_entitlement_method: GET
    mtu : 1400
    olp {
      method: POST
      url: "some@random.com"
      post_data: "random_data"
    }
    olp {
      olp_filter {
        type: MCCMNC
        regex: "200003"
      }
      method: POST
      url: "olp@mccmnc"
      post_data: "post_data"
    }
    mccmnc: "200001"
    mccmnc: "200002"
    mccmnc: "200003"  # Used in FilteredOLP
    mobile_apn {
      apn: "test@test.com"
      type : DEFAULT
      localized_name {
        name: "name200003"
        language: "hi"
      }
      username: "testuser"
      password: "is_public_boohoohoo"
    }
  }
  mvno {
    mvno_filter {
      type: OPERATOR_NAME
      regex: "name200101"
    }
    data {
      uuid: "uuid200101"
      country: "ca"
      localized_name {
        name: "name200101"
        language: "en"
      }
      localized_name {
        name: "name200102"
      }
      requires_roaming: false
      tethering_allowed: false
      mhs_entitlement_url: "uuid200101.com"
      mtu : 1200
      olp {
        method: GET
        url: "someother@random.com"
      }
      # Keep a common MCCMNC, so that it can be used to search for the MNO.
      mccmnc: "200001"
      mccmnc: "200102"
      mobile_apn {
        apn: "test2@test.com"
        type : DEFAULT
        username: "testuser2"
        password: "is_public_boohoohoo_too"
        is_required_by_carrier_spec : true
      }
    }
  }
  mvno {
    mvno_filter {
      type: OPERATOR_NAME
      regex: "name200201"
    }
    data {
      uuid: "uuid200201"
      # Inherit all other information from the MNO.
    }
  }
}
