// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef CRYPTOHOME_ERROR_LOCATIONS_H_
#define CRYPTOHOME_ERROR_LOCATIONS_H_

#include "cryptohome/error/cryptohome_error.h"

namespace cryptohome {

namespace error {

// This file defines the various location code used by CryptohomeError
// Each of the location should only be used in one error site.

// This file is generated and maintained by the cryptohome/error/location_db.py
// utility. Please run this command in cros_sdk to update this file:
// $ /mnt/host/source/src/platform2/cryptohome/error/tool/location_db.py
//       --update

// Note that we should prevent the implicit cast of this enum class to
// ErrorLocation so that if the macro is not used, the compiler will catch it.
enum class ErrorLocationSpecifier : CryptohomeError::ErrorLocation {
  // Start of generated content. Do NOT modify after this line.
  /* ./user_session/real_user_session.cc */
  kLocUserSessionMountEphemeralFailed = 100,
  /* =Obsolete= */
  kLocUserDataAuthMountGuestMountPointBusy = 101,
  /* =Obsolete= */
  kLocUserDataAuthMountGuestNoGuestSession = 102,
  /* =Obsolete= */
  kLocUserDataAuthMountGuestSessionMountFailed = 103,
  /* =Obsolete= */
  kLocUserDataAuthNoEphemeralMountForOwner = 104,
  /* =Obsolete= */
  kLocUserDataAuthEphemeralMountWithoutCreate = 105,
  /* =Obsolete= */
  kLocUserDataAuthMountAuthSessionNotFound = 106,
  /* =Obsolete= */
  kLocUserDataAuthMountAuthSessionNotAuthed = 107,
  /* =Obsolete= */
  kLocUserDataAuthMountNoAccountID = 108,
  /* =Obsolete= */
  kLocUserDataAuthMountCantGetPublicMountSalt = 109,
  /* =Obsolete= */
  kLocUserDataAuthMountNoKeySecret = 110,
  /* =Obsolete= */
  kLocUserDataAuthMountCreateNoKey = 111,
  /* =Obsolete= */
  kLocUserDataAuthMountCreateMultipleKey = 112,
  /* =Obsolete= */
  kLocUserDataAuthMountCreateKeyNotSpecified = 113,
  /* ./challenge_credentials/challenge_credentials_decrypt_operation.cc */
  kLocChalCredDecryptCantStartProcessing = 114,
  /* ./challenge_credentials/challenge_credentials_decrypt_operation.cc */
  kLocChalCredDecryptOperationAborted = 115,
  /* =Obsolete= */
  kLocChalCredDecryptNoSignatureSealingBackend = 116,
  /* ./challenge_credentials/challenge_credentials_decrypt_operation.cc */
  kLocChalCredDecryptNoPubKeySigSize = 117,
  /* ./challenge_credentials/challenge_credentials_decrypt_operation.cc */
  kLocChalCredDecryptSPKIPubKeyMismatch = 118,
  /* ./challenge_credentials/challenge_credentials_decrypt_operation.cc */
  kLocChalCredDecryptSaltProcessingFailed = 119,
  /* ./challenge_credentials/challenge_credentials_decrypt_operation.cc */
  kLocChalCredDecryptNoSalt = 120,
  /* ./challenge_credentials/challenge_credentials_decrypt_operation.cc */
  kLocChalCredDecryptNoSPKIPubKeyDERWhileProcessingSalt = 121,
  /* ./challenge_credentials/challenge_credentials_decrypt_operation.cc */
  kLocChalCredDecryptSaltPrefixIncorrect = 122,
  /* ./challenge_credentials/challenge_credentials_decrypt_operation.cc */
  kLocChalCredDecryptNoSPKIPubKeyDERWhileProcessingSecret = 123,
  /* ./challenge_credentials/challenge_credentials_decrypt_operation.cc */
  kLocChalCredDecryptCreateUnsealingSessionFailed = 124,
  /* ./challenge_credentials/challenge_credentials_decrypt_operation.cc */
  kLocChalCredDecryptSaltResponseNoSignature = 125,
  /* ./challenge_credentials/challenge_credentials_decrypt_operation.cc */
  kLocChalCredDecryptUnsealingResponseNoSignature = 126,
  /* ./challenge_credentials/challenge_credentials_decrypt_operation.cc */
  kLocChalCredDecryptUnsealFailed = 127,
  /* ./challenge_credentials/challenge_credentials_decrypt_operation.cc */
  kLocChalCredDecryptNoSaltSigAlgoWhileProcessingSalt = 128,
  /* =Obsolete= */
  kUserDataAuthInvalidAuthBlockTypeInCreateKeyBlobs = 129,
  /* =Obsolete= */
  kUserDataAuthInvalidAuthBlockTypeInDeriveKeyBlobs = 130,
  /* =Obsolete= */
  kUserDataAuthNoAuthBlockStateInDeriveKeyBlobs = 131,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockInvalidBlockStateInDerive = 132,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockNoSaltInDerive = 133,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockNoTpmKeyInDerive = 134,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockNoScryptDerivedInDerive = 135,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockTpmNotReadyInDerive = 136,
  /* =Obsolete= */
  kLocTpmNotBoundToPcrAuthBlockNoPubKeyHashInDerive = 137,
  /* =Obsolete= */
  kLocTpmNotBoundToPcrAuthBlockDecryptFailedInDerive = 138,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockNoCryptohomeKeyInCreate = 139,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockScryptDeriveFailedInCreate = 140,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockEncryptFailedInCreate = 141,
  /* =Obsolete= */
  kLocTpmNotBoundToPcrAuthBlockReloadKeyFailedInCreate = 142,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockScryptDeriveFailedInDecrypt = 143,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockDecryptFailedInDecrypt = 144,
  /* =Obsolete= */
  kLocTpmNotBoundToPcrAuthBlockReloadKeyFailedInDecrypt = 145,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockVKKConversionFailedInDecrypt = 146,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockScryptDeriveFailedInCreate = 147,
  /* =Obsolete= */
  kLocPinWeaverAuthBlockPCRComputationFailedInCreate = 148,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockInsertCredentialFailedInCreate = 149,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockInvalidBlockStateInDerive = 150,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockNoLabelInDerive = 151,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockNoSaltInDerive = 152,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockDeriveScryptFailedInDerive = 153,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockCheckCredFailedInDerive = 154,
  /* =Obsolete= */
  kLocAuthBlockUtilNoAuthBlockInCreateKeyBlobs = 155,
  /* =Obsolete= */
  kLocAuthBlockUtilCreateFailedInCreateKeyBlobs = 156,
  /* ./auth_blocks/auth_block_utility_impl.cc */
  kLocAuthBlockUtilNoAuthBlockInCreateKeyBlobsAsync = 157,
  /* =Obsolete= */
  kLocAuthBlockUtilNoAuthBlockInDeriveKeyBlobs = 158,
  /* =Obsolete= */
  kLocAuthBlockUtilNoVaultKeysetInDeriveKeyBlobs = 159,
  /* =Obsolete= */
  kLocAuthBlockUtilDeriveFailedInDeriveKeyBlobs = 160,
  /* ./auth_blocks/auth_block_utility_impl.cc */
  kLocAuthBlockUtilNoAuthBlockInDeriveKeyBlobsAsync = 161,
  /* =Obsolete= */
  kLocAuthBlockUtilCHRecoveryUnsupportedInGetAuthBlockWithType = 162,
  /* =Obsolete= */
  kLocAuthBlockUtilMaxValueUnsupportedInGetAuthBlockWithType = 163,
  /* ./auth_blocks/auth_block_utility_impl.cc */
  kLocAuthBlockUtilUnknownUnsupportedInGetAuthBlockWithType = 164,
  /* =Obsolete= */
  kLocAuthBlockUtilNoChalInGetAsyncAuthBlockWithType = 165,
  /* =Obsolete= */
  kLocAuthBlockUtilCHUnsupportedInGetAsyncAuthBlockWithType = 166,
  /* =Obsolete= */
  kLocAuthBlockUtilMaxValueUnsupportedInGetAsyncAuthBlockWithType = 167,
  /* =Obsolete= */
  kLocAuthBlockUtilUnknownUnsupportedInGetAsyncAuthBlockWithType = 168,
  /* =Obsolete= */
  kLocAuthBlockUtilChalCredUnsupportedInCreateKeyBlobsAuthFactor = 169,
  /* =Obsolete= */
  kLocAuthBlockUtilUnsupportedInDeriveKeyBlobs = 170,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockCantCreateRecoveryInCreate = 171,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockGenerateHSMPayloadFailedInCreate = 172,
  /* =Obsolete= */
  kLocRecoveryAuthBlockScryptDeriveFailedInCreate = 173,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockCborConvFailedInCreate = 174,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockRevocationCreateFailedInCreate = 175,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockInvalidBlockStateInDerive = 176,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockCantCreateRecoveryInDerive = 177,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockDecryptFailedInDerive = 178,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockRecoveryFailedInDerive = 179,
  /* =Obsolete= */
  kLocRecoveryAuthBlockScryptDeriveFailedInDerive = 180,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockRevocationDeriveFailedInDerive = 181,
  /* ./auth_blocks/challenge_credential_auth_block.cc */
  kLocChalCredAuthBlockNoKeyServiceInCreate = 182,
  /* ./auth_blocks/challenge_credential_auth_block.cc */
  kLocChalCredAuthBlockNoInputUserInCreate = 183,
  /* ./auth_blocks/challenge_credential_auth_block.cc */
  kLocChalCredAuthBlockNoInputAuthInCreate = 184,
  /* ./auth_blocks/challenge_credential_auth_block.cc */
  kLocChalCredAuthBlockNoInputAlgInCreate = 185,
  /* ./auth_blocks/challenge_credential_auth_block.cc */
  kLocChalCredAuthBlockServiceGenerateFailedInCreate = 186,
  /* ./auth_blocks/challenge_credential_auth_block.cc */
  kLocChalCredAuthBlockCannotCreateScryptInCreate = 187,
  /* ./auth_blocks/challenge_credential_auth_block.cc */
  kLocChalCredAuthBlockScryptDerivationFailedInCreate = 188,
  /* ./auth_blocks/challenge_credential_auth_block.cc */
  kLocChalCredAuthBlockNoKeyServiceInDerive = 189,
  /* ./auth_blocks/challenge_credential_auth_block.cc */
  kLocChalCredAuthBlockInvalidBlockStateInDerive = 190,
  /* ./auth_blocks/challenge_credential_auth_block.cc */
  kLocChalCredAuthBlockNoChallengeInfoInDerive = 191,
  /* ./auth_blocks/challenge_credential_auth_block.cc */
  kLocChalCredAuthBlockNoAlgorithmInfoInDerive = 192,
  /* ./auth_blocks/challenge_credential_auth_block.cc */
  kLocChalCredAuthBlockServiceDeriveFailedInDerive = 193,
  /* =Obsolete= */
  kLocChalCredAuthBlockScryptDeriveFailedInDerive = 194,
  /* =Obsolete= */
  kLocTpmAuthBlockUtilsCryptohomeKeyLoadFailedInPubkeyHash = 195,
  /* ./auth_blocks/tpm_auth_block_utils.cc */
  kLocTpmAuthBlockUtilsGetPubkeyFailedInPubkeyHash = 196,
  /* ./auth_blocks/tpm_auth_block_utils.cc */
  kLocTpmAuthBlockUtilsHashIncorrectInPubkeyHash = 197,
  /* ./auth_blocks/tpm_auth_block_utils.cc */
  kLocTpmAuthBlockUtilsNoTpmKeyInCheckReadiness = 198,
  /* ./auth_blocks/tpm_auth_block_utils.cc */
  kLocTpmAuthBlockUtilsTpmNotOwnedInCheckReadiness = 199,
  /* ./auth_blocks/tpm_auth_block_utils.cc */
  kLocTpmAuthBlockUtilsNoCryptohomeKeyInCheckReadiness = 200,
  /* ./auth_blocks/tpm_auth_block_utils.cc */
  kLocTpmAuthBlockUtilsCHKeyMismatchInCheckReadiness = 201,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockNoUserInputInCreate = 202,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockNoUsernameInCreate = 203,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockNoCryptohomeKeyInCreate = 204,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockScryptDeriveFailedInCreate = 205,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockGetAuthFailedInCreate = 206,
  /* =Obsolete= */
  kLocTpmBoundToPcrAuthBlockReloadKeyFailedInCreate = 207,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockDefaultSealFailedInCreate = 208,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockExtendedSealFailedInCreate = 209,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockNoUserInputInDerive = 210,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockInvalidBlockStateInDerive = 211,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockNoScryptDerivedInDerive = 212,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockNotScryptDerivedInDerive = 213,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockNoSaltInDerive = 214,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockNoTpmKeyInDerive = 215,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockNoExtendedTpmKeyInDerive = 216,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockTpmNotReadyInDerive = 217,
  /* =Obsolete= */
  kLocTpmBoundToPcrAuthBlockNoPubKeyHashInDerive = 218,
  /* =Obsolete= */
  kLocTpmBoundToPcrAuthBlockDecryptFailedInDerive = 219,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockScryptDeriveFailedInDecrypt = 220,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockPreloadFailedInDecrypt = 221,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockUnsealFailedInDecrypt = 222,
  /* ./auth_blocks/double_wrapped_compat_auth_block.cc */
  kLocDoubleWrappedAuthBlockUnsupportedInCreate = 223,
  /* ./auth_blocks/double_wrapped_compat_auth_block.cc */
  kLocDoubleWrappedAuthBlockInvalidBlockStateInDerive = 224,
  /* ./auth_blocks/double_wrapped_compat_auth_block.cc */
  kLocDoubleWrappedAuthBlockTpmDeriveFailedInDerive = 225,
  /* ./auth_blocks/double_wrapped_compat_auth_block.cc */
  kLocDoubleWrappedAuthBlockInvalidBlockStateInAfterScrypt = 226,
  /* =Obsolete= */
  kLocChalCredAuthBlockDerivationFailedInCreate = 227,
  /* =Obsolete= */
  kLocChalCredAuthBlockInvalidBlockStateInDeriveObsolete = 228,
  /* =Obsolete= */
  kLocChalCredAuthBlockScryptDeriveFailedInDeriveObsolete = 229,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockRetryLimitExceededInCreate = 230,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockCryptohomeKeyLoadFailedInCreate = 231,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockSaltWrongSizeInCreate = 232,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockSVKKMDerivedFailedInCreate = 233,
  /* =Obsolete= */
  kLocTpmEccAuthBlockGetAuthFailedInCreate = 234,
  /* =Obsolete= */
  kLocTpmEccAuthBlockCryptohomeKeyReloadFailedInCreate = 235,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockPersistentGetAuthFailedInCreate = 236,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockSVKKMWrongSizeInCreate = 237,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockHVKKMWrongSizeInCreate = 238,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockVKKWrongSizeInCreate = 239,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockHVKKMSealFailedInCreate = 240,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockHVKKMExtendedSealFailedInCreate = 241,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockGetPubkeyHashFailedInCreate = 242,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockInvalidBlockStateInDerive = 243,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockLoadKeyFailedInDerive = 244,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockTpmNotReadyInDerive = 245,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockCantDeriveVKKInDerive = 246,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockPreloadFailedInDeriveVKK = 247,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockScryptDeriveFailedInDeriveVKK = 248,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockWrongSVKKMSizeInDeriveVKK = 249,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockDeriveHVKKMFailedInDeriveVKK = 250,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockWrongHVKKMSizeInDeriveVKK = 251,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockWrongVKKSizeInDeriveVKK = 252,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockGetAuthFailedInDeriveHVKKM = 253,
  /* =Obsolete= */
  kLocTpmEccAuthBlockReloadKeyFailedInDeriveHVKKM = 254,
  /* =Obsolete= */
  kLocTpmEccAuthBlockPersistentGetAuthFailedInDeriveHVKKM = 255,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockUnsealFailedInDeriveHVKKM = 256,
  /* =Obsolete= */
  kLocScryptCompatAuthBlockScryptFailedInCreateHelper = 257,
  /* =Obsolete= */
  kLocScryptCompatAuthBlockParseFailedInParseHeader = 258,
  /* =Obsolete= */
  kLocScryptCompatAuthBlockScryptFailedInParseHeader = 259,
  /* =Obsolete= */
  kLocScryptCompatAuthBlockInputKeyFailedInCreate = 260,
  /* =Obsolete= */
  kLocScryptCompatAuthBlockChapsKeyFailedInCreate = 261,
  /* =Obsolete= */
  kLocScryptCompatAuthBlockResetKeyFailedInCreate = 262,
  /* =Obsolete= */
  kLocScryptCompatAuthBlockInvalidBlockStateInDerive = 263,
  /* =Obsolete= */
  kLocScryptCompatAuthBlockNoWrappedKeysetInDerive = 264,
  /* =Obsolete= */
  kLocScryptCompatAuthBlockInputKeyInDerive = 265,
  /* =Obsolete= */
  kLocScryptCompatAuthBlockChapsKeyInDerive = 266,
  /* =Obsolete= */
  kLocScryptCompatAuthBlockResetKeyInDerive = 267,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManInvalidTreeInInsertCred = 268,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManLabelUnavailableInInsertCred = 269,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManEmptyAuxInInsertCred = 270,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManTpmFailedInInsertCred = 271,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManStoreFailedInInsertCred = 272,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManInvalidTreeInRemoveCred = 273,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManRetrieveLabelFailedInRemoveCred = 274,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManRemoveCredFailedInRemoveCred = 275,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManRemoveLabelFailedInRemoveCred = 276,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManInvalidTreeInCheckSecret = 277,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManInvalidMetadataInCheckSecret = 278,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManStoreLabelFailedInCheckSecret = 279,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManTpmFailedInCheckSecret = 280,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManTreeGetDataFailedInRetrieveLabel = 281,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManNonexistentInRetrieveLabel = 282,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManEmptyAuxInRetrieveLabel = 283,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManConvertTpmError = 284,
  /* ./userdataauth.cc */
  kLocUserDataAuthCreateFailedInStartAuthSession = 285,
  /* =Obsolete= */
  kLocUserDataAuthSessionNotFoundInAuthAuthSession = 286,
  /* =Obsolete= */
  kLocUserDataAuthAuthFailedInAuthAuthSession = 287,
  /* ./userdataauth.cc */
  kLocUserDataAuthSessionNotFoundInExtendAuthSession = 288,
  /* ./userdataauth.cc */
  kLocUserDataAuthExtendFailedInExtendAuthSession = 289,
  /* ./userdataauth.cc */
  kLocUserDataAuthSessionNotFoundInCreatePersistentUser = 290,
  /* ./userdataauth.cc */
  kLocUserDataAuthUserExistsInCreatePersistentUser = 291,
  /* ./userdataauth.cc */
  kLocUserDataAuthCheckExistsFailedInCreatePersistentUser = 292,
  /* ./userdataauth.cc */
  kLocUserDataAuthCreateFailedInCreatePersistentUser = 293,
  /* ./userdataauth.cc */
  kLocUserDataAuthFinalizeFailedInCreatePersistentUser = 294,
  /* ./userdataauth.cc */
  kLocUserDataAuthSessionNotFoundInAuthAuthFactor = 295,
  /* ./auth_session.cc */
  kLocAuthSessionTimedOutInExtend = 296,
  /* ./auth_session.cc */
  kLocAuthSessionCreateUSSFailedInOnUserCreated = 297,
  /* =Obsolete= */
  kLocAuthSessionGetCredFailedInAddCred = 298,
  /* =Obsolete= */
  kLocAuthSessionKioskKeyNotAllowedInAddCred = 299,
  /* =Obsolete= */
  kLocAuthSessionNotAuthedYetInAddCred = 300,
  /* =Obsolete= */
  kLocAuthSessionInvalidBlockTypeInAddKeyset = 301,
  /* =Obsolete= */
  kLocAuthSessionChalCredUnsupportedInAddKeyset = 302,
  /* =Obsolete= */
  kLocAuthSessionPinweaverUnsupportedInAddKeyset = 303,
  /* ./auth_session.cc */
  kLocAuthSessionNullParamInCallbackInAddKeyset = 304,
  /* ./auth_session.cc */
  kLocAuthSessionCreateFailedInAddKeyset = 305,
  /* ./auth_session.cc */
  kLocAuthSessionAddFailedInAddKeyset = 306,
  /* ./auth_session.cc */
  kLocAuthSessionNoFSKeyInAddKeyset = 307,
  /* =Obsolete= */
  kLocAuthSessionNoChallengeInfoInAddKeyset = 308,
  /* ./auth_session.cc */
  kLocAuthSessionAddInitialFailedInAddKeyset = 309,
  /* =Obsolete= */
  kLocAuthSessionGetCredFailedInUpdate = 310,
  /* =Obsolete= */
  kLocAuthSessionUnsupportedKioskKeyInUpdate = 311,
  /* =Obsolete= */
  kLocAuthSessionLabelMismatchInUpdate = 312,
  /* =Obsolete= */
  kLocAuthSessionUnauthedInUpdate = 313,
  /* =Obsolete= */
  kLocAuthSessionInvalidBlockTypeInUpdate = 314,
  /* =Obsolete= */
  kLocAuthSessionChalCredUnsupportedInUpdate = 315,
  /* ./auth_session.cc */
  kLocAuthSessionNullParamInCallbackInUpdateKeyset = 316,
  /* ./auth_session.cc */
  kLocAuthSessionCreateFailedInUpdateKeyset = 317,
  /* ./auth_session.cc */
  kLocAuthSessionUpdateWithBlobFailedInUpdateKeyset = 318,
  /* =Obsolete= */
  kLocAuthSessionGetCredFailedInAuth = 319,
  /* =Obsolete= */
  kLocAuthSessionUnsupportedKeyTypesInAuth = 320,
  /* =Obsolete= */
  kLocAuthSessionGetValidKeysetFailedInAuth = 321,
  /* ./auth_session.cc */
  kLocAuthSessionFactorNotFoundInAuthAuthFactor = 322,
  /* =Obsolete= */
  kLocAuthSessionInputParseFailedInAuthAuthFactor = 323,
  /* =Obsolete= */
  kLocAuthSessionUSSAuthFailedInAuthAuthFactor = 324,
  /* ./auth_session.cc */
  kLocAuthSessionVKConverterFailedInAuthAuthFactor = 325,
  /* ./auth_session.cc */
  kLocAuthSessionInvalidBlockTypeInAuthViaVaultKey = 326,
  /* ./auth_session.cc */
  kLocAuthSessionBlockStateMissingInAuthViaVaultKey = 327,
  /* ./auth_session.cc */
  kLocAuthSessionNullParamInCallbackInLoadVaultKeyset = 328,
  /* ./auth_session.cc */
  kLocAuthSessionDeriveFailedInLoadVaultKeyset = 329,
  /* ./auth_session.cc */
  kLocAuthSessionGetValidKeysetFailedInLoadVaultKeyset = 330,
  /* =Obsolete= */
  kLocAuthSessionNonEmptyKioskKeyInGetCred = 331,
  /* =Obsolete= */
  kLocAuthSessionEmptyPublicMountKeyInGetCred = 332,
  /* ./auth_session.cc */
  kLocAuthSessionUnauthedInAddAuthFactor = 333,
  /* ./auth_session.cc */
  kLocAuthSessionUnknownFactorInAddAuthFactor = 334,
  /* ./auth_session.cc */
  kLocAuthSessionNoInputInAddAuthFactor = 335,
  /* =Obsolete= */
  kLocAuthSessionVKUnsupportedInAddAuthFactor = 336,
  /* =Obsolete= */
  kLocAuthSessionCreateKeyBlobsFailedInAddViaUSS = 337,
  /* =Obsolete= */
  kLocAuthSessionDeriveUSSSecretFailedInPersistToUSS = 338,
  /* ./auth_session.cc */
  kLocAuthSessionAddMainKeyFailedInAddSecretToUSS = 339,
  /* ./auth_session.cc */
  kLocAuthSessionEncryptFailedInPersistToUSS = 340,
  /* ./auth_session.cc */
  kLocAuthSessionPersistFactorFailedInPersistToUSS = 341,
  /* ./auth_session.cc */
  kLocAuthSessionPersistUSSFailedInPersistToUSS = 342,
  /* =Obsolete= */
  kLocAuthSessionAuthFactorAuthFailedInAuthUSS = 343,
  /* =Obsolete= */
  kLocAuthSessionLoadUSSFailedInAuthUSS = 344,
  /* ./auth_session.cc */
  kLocAuthSessionDeriveUSSSecretFailedInLoadUSS = 345,
  /* ./auth_session.cc */
  kLocAuthSessionLoadUSSFailedInLoadUSS = 346,
  /* ./auth_session.cc */
  kLocAuthSessionDecryptUSSFailedInLoadUSS = 347,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockNoUserInputInDerive = 348,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockNoUserInputInCreate = 349,
  /* ./auth_factor/auth_factor_manager.cc */
  kLocGetAuthFactorPathWrongTypeString = 350,
  /* ./auth_factor/auth_factor_manager.cc */
  kLocGetAuthFactorPathInvalidLabel = 351,
  /* ./auth_factor/auth_factor_manager.cc */
  kLocAuthFactorManagerSerializeFailedInSave = 352,
  /* ./auth_factor/auth_factor_manager.cc */
  kLocAuthFactorManagerWriteFailedInSave = 353,
  /* ./auth_factor/auth_factor_manager.cc */
  kLocAuthFactorManagerGetPathFailedInLoad = 354,
  /* ./auth_factor/auth_factor_manager.cc */
  kLocAuthFactorManagerReadFailedInLoad = 355,
  /* ./auth_factor/auth_factor_manager.cc */
  kLocAuthFactorManagerParseFailedInLoad = 356,
  /* =Obsolete= */
  kLocAuthFactorCreateKeyBlobsFailedInCreate = 357,
  /* =Obsolete= */
  kLocAuthSessionDeriveFailedInAuthUSS = 358,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockNoUserInputInCreate = 359,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockNoUsernameInCreate = 360,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockNoUserInputInDerive = 361,
  /* ./vault_keyset.cc */
  kLocVaultKeysetNoResetSeedInEncryptEx = 362,
  /* ./vault_keyset.cc */
  kLocVaultKeysetWrapScryptFailedInEncryptEx = 363,
  /* ./vault_keyset.cc */
  kLocVaultKeysetWrapAESDFailedInEncryptEx = 364,
  /* ./vault_keyset.cc */
  kLocVaultKeysetNotLoadedInDecryptEx = 365,
  /* =Obsolete= */
  kLocVaultKeysetNotLoadedInDecrypt = 366,
  /* =Obsolete= */
  kLocVaultKeysetNoBlockStateInDecryptVK = 367,
  /* =Obsolete= */
  kLocVaultKeysetUnknownBlockTypeInDecryptVK = 368,
  /* =Obsolete= */
  kLocVaultKeysetDeriveFailedInDecryptVK = 369,
  /* =Obsolete= */
  kLocVaultKeysetUnwrapVKFailedInDecryptVK = 370,
  /* ./vault_keyset.cc */
  kLocVaultKeysetKeysetDecryptFailedInUnwrapVKK = 371,
  /* ./vault_keyset.cc */
  kLocVaultKeysetKeysetParseFailedInUnwrapVKK = 372,
  /* ./vault_keyset.cc */
  kLocVaultKeysetChapsDecryptFailedInUnwrapVKK = 373,
  /* ./vault_keyset.cc */
  kLocVaultKeysetResetSeedDecryptFailedInUnwrapVKK = 374,
  /* ./vault_keyset.cc */
  kLocVaultKeysetKeysetDecryptFailedInUnwrapScrypt = 375,
  /* ./vault_keyset.cc */
  kLocVaultKeysetChapsDecryptFailedInUnwrapScrypt = 376,
  /* ./vault_keyset.cc */
  kLocVaultKeysetResetSeedDecryptFailedInUnwrapScrypt = 377,
  /* ./vault_keyset.cc */
  kLocVaultKeysetBlobUnderflowInUnwrapScrypt = 378,
  /* ./vault_keyset.cc */
  kLocVaultKeysetKeysetParseFailedInUnwrapScrypt = 379,
  /* ./vault_keyset.cc */
  kLocVaultKeysetMissingFieldInWrapAESD = 380,
  /* ./vault_keyset.cc */
  kLocVaultKeysetSerializationFailedInWrapAESD = 381,
  /* ./vault_keyset.cc */
  kLocVaultKeysetEncryptFailedInWrapAESD = 382,
  /* ./vault_keyset.cc */
  kLocVaultKeysetEncryptChapsFailedInWrapAESD = 383,
  /* ./vault_keyset.cc */
  kLocVaultKeysetEncryptResetSeedInWrapAESD = 384,
  /* ./vault_keyset.cc */
  kLocVaultKeysetLENotSupportedInWrapScrypt = 385,
  /* ./vault_keyset.cc */
  kLocVaultKeysetSerializeFailedInWrapScrypt = 386,
  /* ./vault_keyset.cc */
  kLocVaultKeysetEncryptKeysetFailedInWrapScrypt = 387,
  /* ./vault_keyset.cc */
  kLocVaultKeysetEncryptChapsFailedInWrapScrypt = 388,
  /* ./vault_keyset.cc */
  kLocVaultKeysetEncryptResetSeedFailedInWrapScrypt = 389,
  /* ./vault_keyset.cc */
  kLocVaultKeysetUnwrapVKKFailedInUnwrapVK = 390,
  /* ./vault_keyset.cc */
  kLocVaultKeysetUnwrapScryptFailedInUnwrapVK = 391,
  /* ./vault_keyset.cc */
  kLocVaultKeysetInvalidCombinationInUnwrapVK = 392,
  /* =Obsolete= */
  kLocVaultKeysetNoResetSeedInEncrypt = 393,
  /* =Obsolete= */
  kLocVaultKeysetUnknownBlockTypeInEncryptVK = 394,
  /* =Obsolete= */
  kLocVaultKeysetCreateFailedInEncryptVK = 395,
  /* =Obsolete= */
  kLocVaultKeysetWrapScryptFailedInEncryptVK = 396,
  /* =Obsolete= */
  kLocVaultKeysetWrapAESDFailedInEncryptVK = 397,
  /* ./challenge_credentials/challenge_credentials_operation.cc */
  kLocChalCredOperationNoResponseInOnSigResponse = 398,
  /* ./challenge_credentials/challenge_credentials_operation.cc */
  kLocChalCredOperationResponseInvalidInOnSigResponse = 399,
  /* ./challenge_credentials/challenge_credentials_verify_key_operation.cc */
  kLocChalCredVerifyNoAlgorithm = 400,
  /* ./challenge_credentials/challenge_credentials_verify_key_operation.cc */
  kLocChalCredVerifyNoAlgorithmChosen = 401,
  /* ./challenge_credentials/challenge_credentials_verify_key_operation.cc */
  kLocChalCredVerifyGetRandomFailed = 402,
  /* ./challenge_credentials/challenge_credentials_verify_key_operation.cc */
  kLocChalCredVerifyAborted = 403,
  /* ./challenge_credentials/challenge_credentials_verify_key_operation.cc */
  kLocChalCredVerifyChallengeFailed = 404,
  /* ./challenge_credentials/challenge_credentials_verify_key_operation.cc */
  kLocChalCredVerifyInvalidSignature = 405,
  /* ./challenge_credentials/challenge_credentials_helper_impl.cc */
  kLocChalCredHelperConcurrencyNotAllowed = 406,
  /* ./challenge_credentials/challenge_credentials_generate_new_operation.cc */
  kLocChalCredNewAborted = 407,
  /* ./challenge_credentials/challenge_credentials_generate_new_operation.cc */
  kLocChalCredNewNoBackend = 408,
  /* ./challenge_credentials/challenge_credentials_generate_new_operation.cc */
  kLocChalCredNewNoAlgorithm = 409,
  /* ./challenge_credentials/challenge_credentials_generate_new_operation.cc */
  kLocChalCredNewGenerateRandomSaltFailed = 410,
  /* ./challenge_credentials/challenge_credentials_generate_new_operation.cc */
  kLocChalCredNewCantChooseSaltSignatureAlgorithm = 411,
  /* ./challenge_credentials/challenge_credentials_generate_new_operation.cc */
  kLocChalCredNewSealFailed = 412,
  /* ./key_challenge_service_impl.cc */
  kLocKeyChallengeServiceEmptyResponseInChallengeKey = 413,
  /* ./key_challenge_service_impl.cc */
  kLocKeyChallengeServiceParseFailedInChallengeKey = 414,
  /* ./key_challenge_service_impl.cc */
  kLocKeyChallengeServiceKnownDBusErrorInChallengeKey = 415,
  /* ./key_challenge_service_impl.cc */
  kLocKeyChallengeServiceUnknownDBusErrorInChallengeKey = 416,
  /* ./key_challenge_service_impl.cc */
  kLocKeyChallengeServiceInvalidDBusNameInChallengeKey = 417,
  /* =Obsolete= */
  kLocUserDataAuthChalCredFailedInChalRespMount = 418,
  /* =Obsolete= */
  kLocUserDataAuthNoSessionInTryLiteChalRespCheckKey = 419,
  /* =Obsolete= */
  kLocUserDataAuthNoServiceInTryLiteChalRespCheckKey = 420,
  /* =Obsolete= */
  kLocUserDataAuthNoKeyInfoInTryLiteChalRespCheckKey = 421,
  /* =Obsolete= */
  kLocUserDataAuthMultipleKeyInTryLiteChalRespCheckKey = 422,
  /* ./keyset_management.cc */
  kLocKeysetManagementGetKeysetsFailedInGetValidKeyset = 423,
  /* ./keyset_management.cc */
  kLocKeysetManagementNoKeysetsInGetValidKeyset = 424,
  /* ./keyset_management.cc */
  kLocKeysetManagementKeysetNotDecryptedInGetValidKeyset = 425,
  /* ./keyset_management.cc */
  kLocKeysetManagementNoKeysetsDecryptedInGetValidKeyset = 426,
  /* ./keyset_management.cc */
  kLocKeysetManagementDecryptFailedInGetValidKeyset = 427,
  /* =Obsolete= */
  kLocKeysetManagementEncryptFailedInAddInitial = 428,
  /* =Obsolete= */
  kLocKeysetManagementSaveFailedInAddInitial = 429,
  /* ./keyset_management.cc */
  kLocKeysetManagementEncryptFailedInEncryptAndSaveKeyset = 430,
  /* ./keyset_management.cc */
  kLocKeysetManagementEncryptAndSaveFailedInReSaveKeyset = 431,
  /* ./keyset_management.cc */
  kLocKeysetManagementSaveFailedInEncryptAndSaveKeyset = 432,
  /* ./keyset_management.cc */
  kLocKeysetManagementVKDuplicateLabelAddKeyset = 433,
  /* ./keyset_management.cc */
  kLocKeysetManagementKeyQuotaExceededAddKeyset = 434,
  /* ./keyset_management.cc */
  kLocKeysetManagementFailedEncryptAndSaveKeysetWithKeyBlobs = 435,
  /* ./keyset_management.cc */
  kLocKeysetManagementLabelNotFoundUpdateKeysetWithKeyBlobs = 436,
  /* ./keyset_management.cc */
  kLocKeysetManagementInvalidIndexInRemoveKeyset = 437,
  /* ./keyset_management.cc */
  kLocKeysetManagementDeleteFailedInRemoveKeyset = 438,
  /* =Obsolete= */
  kLocUserDataAuthRemoveUnrecoverableFailedInContinueMount = 439,
  /* =Obsolete= */
  kLocUserDataAuthCreateKeyBlobsFailedInLoadVK = 440,
  /* =Obsolete= */
  kLocUserDataAuthAddInitialKeysetFailedInLoadVK = 441,
  /* =Obsolete= */
  kLocUserDataAuthGetKeyLabelsFailedInLoadVK = 442,
  /* =Obsolete= */
  kLocUserDataAuthNoKeyLabelUsableInLoadVK = 443,
  /* =Obsolete= */
  kLocUserDataAuthSessionActiveInAttemptUserMountCred = 444,
  /* =Obsolete= */
  kLocUserDataAuthEphemeralFailedInAttemptUserMountCred = 445,
  /* =Obsolete= */
  kLocUserDataAuthCheckExistenceFailedInAttemptUserMountCred = 446,
  /* =Obsolete= */
  kLocUserDataAuthAccountMissingInAttemptUserMountCred = 447,
  /* =Obsolete= */
  kLocUserDataAuthCreateFailedInAttemptUserMountCred = 448,
  /* =Obsolete= */
  kLocUserDataAuthLoadVKFailedInAttemptUserMountCred = 449,
  /* =Obsolete= */
  kLocUserDataAuthMountVaultFailedInAttemptUserMountCred = 450,
  /* =Obsolete= */
  kLocUserDataAuthSessionActiveInAttemptUserMountAS = 451,
  /* =Obsolete= */
  kLocUserDataAuthEphemeralFailedInAttemptUserMountAS = 452,
  /* =Obsolete= */
  kLocUserDataAuthNotAuthedInAttemptUserMountAS = 453,
  /* =Obsolete= */
  kLocUserDataAuthMountVaultFailedInAttemptUserMountAS = 454,
  /* ./user_session/real_user_session.cc */
  kLocUserSessionMountFailedInMountVault = 455,
  /* ./user_session/real_user_session.cc */
  kLocUserSessionOwnerNotSupportedInMountEphemeral = 456,
  /* ./user_session/real_user_session.cc */
  kLocUserSessionMountFailedInMountEphemeral = 457,
  /* ./auth_session.cc */
  kLocAuthSessionAddResetSecretFailedInAddSecretToUSS = 458,
  /* ./auth_blocks/auth_block_utility_impl.cc */
  kLocAuthBlockStateInvalidInGenerateRecoveryRequest = 459,
  /* ./auth_blocks/auth_block_utility_impl.cc */
  kLocFailedDeserializeHsmPayloadInGenerateRecoveryRequest = 460,
  /* ./auth_blocks/auth_block_utility_impl.cc */
  kLocFailedParseEpochResponseInGenerateRecoveryRequest = 461,
  /* ./auth_blocks/auth_block_utility_impl.cc */
  kLocFailedToGetRecoveryCryptoBackendInGenerateRecoveryRequest = 462,
  /* ./auth_blocks/auth_block_utility_impl.cc */
  kLocFailedGenerateRecoveryRequest = 463,
  /* ./userdataauth.cc */
  kLocUserDataAuthSessionNotFoundInGetRecoveryRequest = 464,
  /* ./auth_session.cc */
  kLocAuthSessionFactorNotFoundInGetRecoveryRequest = 465,
  /* ./auth_session.cc */
  kLocNoRecoveryAuthBlockStateInGetRecoveryRequest = 466,
  /* ./auth_session.cc */
  kLocCryptoFailedInGenerateRecoveryRequest = 467,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockNoUserInputInCreate = 468,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockNoUsernameInCreate = 469,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockNoResetSecretOrResetSeedInCreate = 470,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockNoUserInputInDerive = 471,
  /* ./keyset_management.cc */
  kLocKeysetManagementEncryptAndSaveFailedInAddInitialKeyset = 472,
  /* ./userdataauth.cc */
  kLocUserDataAuthSessionNotFoundInGetAuthedAS = 473,
  /* ./userdataauth.cc */
  kLocUserDataAuthSessionNotAuthedInGetAuthedAS = 474,
  /* ./userdataauth.cc */
  kLocUserDataAuthGuestAlreadyMountedInGetMountableUS = 475,
  /* ./userdataauth.cc */
  kLocUserDataAuthSessionAlreadyMountedInGetMountableUS = 476,
  /* =Obsolete= */
  kLocUserDataAuthPrepareVaultFailedInPrepareForMigration = 477,
  /* ./userdataauth.cc */
  kLocUserDataAuthOtherSessionActiveInPrepareGuestVault = 478,
  /* ./userdataauth.cc */
  kLocUserDataAuthMountFailedInPrepareGuestVault = 479,
  /* ./userdataauth.cc */
  kLocUserDataAuthNoAuthSessionInPrepareEphemeralVault = 480,
  /* ./userdataauth.cc */
  kLocUserDataAuthGetSessionFailedInPrepareEphemeralVault = 481,
  /* ./userdataauth.cc */
  kLocUserDataAuthMountFailedInPrepareEphemeralVault = 482,
  /* ./userdataauth.cc */
  kLocUserDataAuthNoAuthSessionInPreparePersistentVault = 483,
  /* ./userdataauth.cc */
  kLocUserDataAuthNonExistentInPreparePersistentVault = 484,
  /* ./userdataauth.cc */
  kLocUserDataAuthGetSessionFailedInPreparePersistentVault = 485,
  /* ./userdataauth.cc */
  kLocUserDataAuthMountFailedInPreparePersistentVault = 486,
  /* ./userdataauth.cc */
  kLocUserDataAuthNoAuthSessionInAddAuthFactor = 487,
  /* =Obsolete= */
  kLocUserDataAuthAddAuthFactorFailedInAddAuthFactor = 488,
  /* ./user_secret_stash/storage.cc */
  kLocUSSStorageWriteFailedInPersist = 489,
  /* ./user_secret_stash/storage.cc */
  kLocUSSStorageReadFailedInLoadPersisted = 490,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSNoFEKInGetFSKeyFromPayload = 491,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSNoFNEKInGetFSKeyFromPayload = 492,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSNoFEKSaltInGetFSKeyFromPayload = 493,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSNoFNEKSaltInGetFSKeyFromPayload = 494,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSNoFEKSigInGetFSKeyFromPayload = 495,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSNoFNEKSigInGetFSKeyFromPayload = 496,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSNoChapsKeyInGetFSKeyFromPayload = 497,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSDeserializeFailedInGetContainerFromFB = 498,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSNoAlgInGetContainerFromFB = 499,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSUnknownAlgInGetContainerFromFB = 500,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSNoCiphertextInGetContainerFromFB = 501,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSNoIVInGetContainerFromFB = 502,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSIVWrongSizeInGetContainerFromFB = 503,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSNoGCMTagInGetContainerFromFB = 504,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSTagWrongSizeInGetContainerFromFB = 505,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSEmptyWrappingIDInUnwrapMKFromBlocks = 506,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSWrongWKSizeInUnwrapMKFromBlocks = 507,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSWrappedBlockNotFoundInUnwrapMKFromBlocks = 508,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSUnknownAlgInUnwrapMKFromBlocks = 509,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSEmptyEncKeyInUnwrapMKFromBlocks = 510,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSWrongIVSizeInUnwrapMKFromBlocks = 511,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSWrongTagSizeInUnwrapMKFromBlocks = 512,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSDecryptFailedInUnwrapMKFromBlocks = 513,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSInvalidKeySizeInFromEncContainer = 514,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSGetFromFBFailedInFromEncContainer = 515,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSFromPayloadFailedInFromEncContainer = 516,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSAesGcmFailedInFromEncPayload = 517,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSDeserializeFailedInFromEncPayload = 518,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSGetFSKeyFailedInFromEncPayload = 519,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSGetFromFBFailedInFromEncContainerWithWK = 520,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSUnwrapMKFailedInFromEncContainerWithWK = 521,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSFromPayloadFailedInFromEncContainerWithWK = 522,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSUnwrapMKFailedInUnwrapMK = 523,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSMainKeyEmptyInAddWrappedMainKey = 524,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSWrappingIDEmptyInAddWrappedMainKey = 525,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSWrappingWrongSizeInAddWrappedMainKey = 526,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSDuplicateWrappingInAddWrappedMainKey = 527,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSEncryptFailedInAddWrappedMainKey = 528,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSPayloadSerializeFailedInGetEncContainer = 529,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSPayloadEncryptFailedInGetEncContainer = 530,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSContainerSerializeFailedInGetEncContainer = 531,
  /* ./userdataauth.cc */
  kLocUserDataAuthNotConfiguredInStartAuthSession = 532,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockCantParseEpochResponseInDerive = 533,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockCantParseResponseInDerive = 534,
  /* ./auth_session.cc */
  kLocWrongAuthFactorInGetRecoveryRequest = 535,
  /* =Obsolete= */
  kLocAuthSessionEmptyKeyLabelInAuth = 536,
  /* =Obsolete= */
  kLocUserDataAuthAuthBlockUtilityNotValidForChallenge = 537,
  /* =Obsolete= */
  kLocAuthSessionAddCredentialInvalidAuthInput = 538,
  /* =Obsolete= */
  kLocAuthSessionAuthenticateInvalidAuthInput = 539,
  /* ./auth_session.cc */
  kLocAuthSessionVKConverterFailsInAddAuthFactor = 540,
  /* =Obsolete= */
  kLocAuthSessionTryAddInitialPinInAddAuthfActor = 541,
  /* =Obsolete= */
  kLocAuthBlockUtilGetAuthBlockTypeFailedInCreateKeyBlobsAuthFactor = 542,
  /* =Obsolete= */
  kLocScryptAuthBlockScryptFailedInCreate = 543,
  /* ./auth_blocks/scrypt_auth_block.cc */
  kLocScryptAuthBlockInvalidBlockStateInDerive = 544,
  /* ./auth_blocks/scrypt_auth_block.cc */
  kLocScryptAuthBlockNoSaltInDerive = 545,
  /* ./auth_blocks/scrypt_auth_block.cc */
  kLocScryptAuthBlockNofactorsInDerive = 546,
  /* ./auth_blocks/scrypt_auth_block.cc */
  kLocScryptAuthBlockScryptFailedInDeriveFromSalt = 547,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockGetAuthValueFailedInDecrypt = 548,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockObscureMessageFailedInCreate = 549,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockUnobscureMessageFailedInDecrypt = 550,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockNoUsernameInCreate = 551,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockNoUsernameInDerive = 552,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManPinWeaverFailedInCheckSecret = 553,
  /* =Obsolete= */
  kLocUserDataAuthNoTPMInInitChalRespAuth = 554,
  /* =Obsolete= */
  kLocUserDataAuthTPMNotReadyInInitChalRespAuth = 555,
  /* =Obsolete= */
  kLocUserDataAuthCantQueryROCAVulnInInitChalRespAuth = 556,
  /* =Obsolete= */
  kLocUserDataAuthROCAVulnerableInInitChalRespAuth = 557,
  /* =Obsolete= */
  kLocUserDataAuthNoDBusInInitChalRespAuth = 558,
  /* =Obsolete= */
  kLocUserDataAuthNoDelegateInInitChalRespAuth = 559,
  /* =Obsolete= */
  kLocUserDataAuthInitFailedInInitAuthBlockUtilChalResp = 560,
  /* =Obsolete= */
  kLocUserDataAuthNoDelegateInInitAuthBlockUtilChalResp = 561,
  /* =Obsolete= */
  kLocUserDataAuthNokeyInfoInInitAuthBlockUtilChalResp = 562,
  /* =Obsolete= */
  kLocUserDataAuthMultipleKeysInInitAuthBlockUtilChalResp = 563,
  /* =Obsolete= */
  kLocUserDataAuthCreateFailedInInitAuthBlockUtilChalResp = 564,
  /* =Obsolete= */
  kLocUserDataAuthInitChalRespAuthFailedInDoChalRespMount = 565,
  /* =Obsolete= */
  kLocUserDataAuthNoChalRespKeyInfoInDoChalRespMount = 566,
  /* =Obsolete= */
  kLocUserDataAuthMultipleKeysInDoChalRespMount = 567,
  /* =Obsolete= */
  kLocUserDataAuthNoDelegateInDoChalRespMount = 568,
  /* =Obsolete= */
  kLocUserDataAuthNoChalRespServiceInDoChalRespMount = 569,
  /* =Obsolete= */
  kLocUserDataAuthAccountNotFoundInDoChalRespMount = 570,
  /* =Obsolete= */
  kLocUserDataAuthNoChalRespVKInDoChalRespMount = 571,
  /* =Obsolete= */
  kLocUserDataAuthAccountNotFoundInContinueMountWithCred = 572,
  /* =Obsolete= */
  kLocUserDataAuthGuestMountPointBusyInContinueMountWithCred = 573,
  /* =Obsolete= */
  kLocUserDataAuthCantCreateSessionInContinueMountWithCred = 574,
  /* =Obsolete= */
  kLocUserDataAuthPublicMountPointBusyInContinueMountWithCred = 575,
  /* =Obsolete= */
  kLocUserDataAuthEpheMountPointBusyInContinueMountWithCred = 576,
  /* =Obsolete= */
  kLocUserDataAuthNoCreateForEphemeralInContinueMountWithCred = 577,
  /* =Obsolete= */
  kLocUserDataAuthCredVerifyFailedInContinueMountWithCred = 578,
  /* =Obsolete= */
  kLocUserDataAuthMountFailedInContinueMountWithCred = 579,
  /* =Obsolete= */
  kLocUserDataAuthInitChalRespFailedInAddCredentials = 580,
  /* ./userdataauth.cc */
  kLocUserDataAuthRemoveAllMountsFailedInUnmount = 581,
  /* ./userdataauth.cc */
  kLocUserDataAuthNoIDInListKeys = 582,
  /* ./userdataauth.cc */
  kLocUserDataAuthInvalidIDInListKeys = 583,
  /* ./userdataauth.cc */
  kLocUserDataAuthUserNonexistentInListKeys = 584,
  /* ./userdataauth.cc */
  kLocUserDataAuthListFailedInListKeys = 585,
  /* ./userdataauth.cc */
  kLocUserDataAuthNoIDInRemove = 586,
  /* =Obsolete= */
  kLocUserDataAuthInvalidAuthSessionInRemove = 587,
  /* ./userdataauth.cc */
  kLocUserDataAuthNoAccountIdWithAuthSessionInRemove = 588,
  /* ./userdataauth.cc */
  kLocUserDataAuthUserActiveInRemove = 589,
  /* ./userdataauth.cc */
  kLocUserDataAuthRemoveFailedInRemove = 590,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockCheckCredLockedInDerive = 591,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManInvalidTreeInGetCredentialMetadata = 592,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManRetrieveLabelFailedInGetCredentialMetadata = 593,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManPinWeaverFailedInGetDelayInSeconds = 594,
  /* ./auth_blocks/auth_block_utility_impl.cc */
  kLocAuthBlockUtilUnsupportedInPrepareAuthBlockForRemoval = 595,
  /* ./auth_blocks/auth_block_utility_impl.cc */
  kLocAuthBlockUtilNoAuthBlockInPrepareForRemoval = 596,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockInvalidStateInPrepareForRemoval = 597,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockNoRevocationInPrepareForRemoval = 598,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockNoLEManagerInPrepareForRemoval = 599,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockRevocationFailedInPrepareForRemoval = 600,
  /* ./userdataauth.cc */
  kLocUserDataAuthSessionNotFoundInRemoveAuthFactor = 601,
  /* ./auth_session.cc */
  kLocAuthSessionFactorNotFoundInRemoveAuthFactor = 602,
  /* ./auth_session.cc */
  kLocAuthSessionLastFactorInRemoveAuthFactor = 603,
  /* ./auth_session.cc */
  kLocAuthSessionRemoveFactorFailedInRemoveAuthFactor = 604,
  /* =Obsolete= */
  kLocAuthFactorPrepareForRemovalFailed = 605,
  /* ./auth_factor/auth_factor_manager.cc */
  kLocAuthFactorManagerGetPathFailedInSave = 606,
  /* ./auth_factor/auth_factor_manager.cc */
  kLocAuthFactorManagerGetPathFailedInRemove = 607,
  /* ./auth_factor/auth_factor_manager.cc */
  kLocAuthFactorManagerPrepareForRemovalFailedInRemove = 608,
  /* ./auth_factor/auth_factor_manager.cc */
  kLocAuthFactorManagerDeleteFailedInRemove = 609,
  /* ./auth_session.cc */
  kLocAuthSessionRemoveVKFailedInRemoveAuthFactor = 610,
  /* ./auth_session.cc */
  kLocAuthSessionRemoveMainKeyFailedInRemoveSecretFromUss = 611,
  /* ./auth_session.cc */
  kLocAuthSessionEncryptFailedInRemoveAuthFactor = 612,
  /* ./auth_session.cc */
  kLocAuthSessionPersistUSSFailedInRemoveAuthFactor = 613,
  /* ./auth_session.cc */
  kLocAuthSessionInvalidBlockTypeInAddAuthFactor = 614,
  /* ./auth_session.cc */
  kLocAuthSessionNullParamInPersistToUSS = 615,
  /* ./auth_session.cc */
  kLocAuthSessionCreateFailedInPersistToUSS = 616,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockPasskeyToAesKeyFailedInDecrypt = 617,
  /* ./auth_factor/auth_factor_manager.cc */
  kLocAuthFactorManagerLoadFailedInUpdate = 618,
  /* ./auth_factor/auth_factor_manager.cc */
  kLocAuthFactorManagerSaveFailedInUpdate = 619,
  /* ./auth_factor/auth_factor_manager.cc */
  kLocAuthFactorManagerPrepareForRemovalFailedInUpdate = 620,
  /* ./auth_session.cc */
  kLocAuthSessionInvalidBlockTypeInAuthViaUSS = 621,
  /* ./auth_session.cc */
  kLocAuthSessionNullParamInLoadUSS = 622,
  /* ./auth_session.cc */
  kLocAuthSessionDeriveFailedInLoadUSS = 623,
  /* ./auth_blocks/challenge_credential_auth_block.cc */
  kLocChalCredAuthBlockNoInputAuthInDerive = 624,
  /* ./challenge_credentials/challenge_credentials_decrypt_operation.cc */
  kLocChalCredDecryptNoHwsecBackend = 625,
  /* ./challenge_credentials/challenge_credentials_decrypt_operation.cc */
  kLocChalCredDecryptUnsealingResponseNoChallenge = 626,
  /* ./challenge_credentials/challenge_credentials_generate_new_operation.cc */
  kLocChalCredGenRandFailed = 627,
  /* =Obsolete= */
  kLocUserDataAuthHwsecNotReadyInInitChalRespAuth = 628,
  /* ./userdataauth.cc */
  kLocUserDataAuthUserNonexistentInListAuthFactors = 629,
  /* ./userdataauth.cc */
  kLocUserDataAuthNoAuthSessionInUpdateAuthFactor = 630,
  /* ./auth_session.cc */
  kLocAuthSessionRemoveFromUssFailedInRemoveAuthFactor = 631,
  /* ./auth_session.cc */
  kLocAuthSessionUnauthedInUpdateAuthFactor = 632,
  /* ./auth_session.cc */
  kLocAuthSessionNoOldLabelInUpdateAuthFactor = 633,
  /* ./auth_session.cc */
  kLocAuthSessionFactorNotFoundInUpdateAuthFactor = 634,
  /* ./auth_session.cc */
  kLocAuthSessionUnknownFactorInUpdateAuthFactor = 635,
  /* ./auth_session.cc */
  kLocAuthSessionDifferentLabelInUpdateAuthFactor = 636,
  /* ./auth_session.cc */
  kLocAuthSessionDifferentTypeInUpdateAuthFactor = 637,
  /* ./auth_session.cc */
  kLocAuthSessionNoInputInUpdateAuthFactor = 638,
  /* ./auth_session.cc */
  kLocAuthSessionInvalidBlockTypeInUpdateAuthFactor = 639,
  /* ./auth_session.cc */
  kLocAuthSessionAddVaultKeysetFailedinAddAuthFactor = 640,
  /* ./auth_session.cc */
  kLocAuthSessionNullParamInUpdateViaUSS = 641,
  /* ./auth_session.cc */
  kLocAuthSessionCreateFailedInUpdateViaUSS = 642,
  /* =Obsolete= */
  kLocAuthSessionDeriveUSSSecretFailedInUpdateViaUSS = 643,
  /* ./auth_session.cc */
  kLocAuthSessionRemoveFromUSSFailedInUpdateViaUSS = 644,
  /* ./auth_session.cc */
  kLocAuthSessionAddToUSSFailedInUpdateViaUSS = 645,
  /* ./auth_session.cc */
  kLocAuthSessionEncryptFailedInUpdateViaUSS = 646,
  /* ./auth_session.cc */
  kLocAuthSessionPersistFactorFailedInUpdateViaUSS = 647,
  /* ./auth_session.cc */
  kLocAuthSessionPersistUSSFailedInUpdateViaUSS = 648,
  /* ./auth_session.cc */
  kLocAuthSessionAddToUssFailedInPersistToUSS = 649,
  /* =Obsolete= */
  kLocAuthSessionAddBackupVKFailedInPersistToUSS = 650,
  /* ./auth_session.cc */
  kLocAuthSessionUnauthedInRemoveAuthFactor = 651,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManInvalidMetadataInGetCredentialMetadata = 652,
  /* ./userdataauth.cc */
  kLocUserDataAuthOtherSessionActiveInPrepareEphemeralVault = 653,
  /* ./userdataauth.cc */
  kLocUserDataAuthNoIntentInStartAuthSession = 654,
  /* =Obsolete= */
  kLocUserDataAuthNoKeyChallengeServiceInAddAuthFactor = 655,
  /* =Obsolete= */
  kLocUserDataAuthNoKeyChallengeServiceInAuthAuthFactor = 656,
  /* =Obsolete= */
  kLocNoWrappedSeedInAuthInputForAdd = 657,
  /* =Obsolete= */
  kLocEmptySeedInAuthInputForAdd = 658,
  /* =Obsolete= */
  kLocAuthSessionInvalidBlockTypeInUpdateAuthFactorViaVK = 659,
  /* ./auth_session.cc */
  kLocAuthSessionConverterFailsInUpdateFactorViaVK = 660,
  /* ./auth_session.cc */
  kLocCreateFailedInAuthInputForAuth = 661,
  /* ./auth_session.cc */
  kLocCreateFailedInAuthInputForAdd = 662,
  /* ./auth_session.cc */
  kLocNoVkInAuthInputForAdd = 663,
  /* ./auth_session.cc */
  kLocNoUserInputInAddFactorForEphemeral = 664,
  /* ./auth_session.cc */
  kLocVerifierAlreadySetInAddFactorForEphemeral = 665,
  /* ./auth_session.cc */
  kLocVerifierSettingErrorInAddFactorForEphemeral = 666,
  /* ./userdataauth.cc */
  kLocUserDataAuthNoIDInResetAppContainer = 667,
  /* ./userdataauth.cc */
  kLocUserDataAuthUserInactiveInResetAppContainer = 668,
  /* ./userdataauth.cc */
  kLocUserDataAuthUserFailedResetAppContainer = 669,
  /* ./auth_session.cc */
  kLocAuthSessionNoAuthFactorTypeInAuthAuthFactor = 670,
  /* ./userdataauth.cc */
  kLocUserDataAuthFinalizeFailedInPrepareEphemeralVault = 671,
  /* ./auth_session.cc */
  kLocAuthSessionMismatchedAuthTypes = 672,
  /* ./auth_blocks/scrypt_auth_block.cc */
  kLocScryptAuthBlockScryptFailedDerivedKeyInCreate = 673,
  /* ./auth_blocks/scrypt_auth_block.cc */
  kLocScryptAuthBlockInputKeyFailedInCreate = 674,
  /* ./auth_blocks/scrypt_auth_block.cc */
  kLocScryptAuthBlockChapsKeyFailedInCreate = 675,
  /* ./auth_blocks/scrypt_auth_block.cc */
  kLocScryptAuthBlockResetKeyFailedInCreate = 676,
  /* ./auth_blocks/scrypt_auth_block.cc */
  kLocScryptAuthBlockScryptFailedInDeriveFromChapsSalt = 677,
  /* ./auth_blocks/scrypt_auth_block.cc */
  kLocScryptAuthBlockScryptFailedInDeriveFromResetSeedSalt = 678,
  /* ./vault_keyset.cc */
  kLocVaultKeysetAuthBlockStateFailedInWrapScrypt = 679,
  /* =Obsolete= */
  kLocLECredManInvalidTreeInGetExpirationInSeconds = 680,
  /* =Obsolete= */
  kLocLECredManRetrieveLabelFailedInGetExpirationInSeconds = 681,
  /* =Obsolete= */
  kLocLECredManInvalidMetadataInGetExpirationInSeconds = 682,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManPinWeaverFailedInGetExpirationInSeconds = 683,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManInvalidTreeInStartBiometricsAuth = 684,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManInvalidMetadataInStartBiometricsAuth = 685,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManPinWeaverFailedInStartBiometricsAuth = 686,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManStoreLabelFailedInStartBiometricsAuth = 687,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManTpmFailedInStartBiometricsAuth = 688,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManInvalidOutputInStartBiometricsAuth = 689,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManInvalidParamInInsertCred = 690,
  /* ./auth_session.cc */
  kLocAuthSessionRemoveSameVKInRemoveAuthFactor = 691,
  /* ./auth_session.cc */
  kLocAuthSessionRemoveAuthFactorViaUserSecretStashFailed = 692,
  /* ./auth_session.cc */
  kLocAuthSessionVKNotFoundInRemoveKeysetByLabel = 693,
  /* ./auth_blocks/revocation.cc */
  kLocRevocationNoVkkKeyInCreate = 694,
  /* ./auth_blocks/revocation.cc */
  kLocRevocationDeriveSecretsFailedInCreate = 695,
  /* ./auth_blocks/revocation.cc */
  kLocRevocationInsertCredentialFailedInCreate = 696,
  /* ./auth_blocks/revocation.cc */
  kLocRevocationHkdfFailedInCreate = 697,
  /* ./auth_blocks/revocation.cc */
  kLocRevocationNoVkkKeyInDerive = 698,
  /* ./auth_blocks/revocation.cc */
  kLocRevocationNoLeLabelInDerive = 699,
  /* ./auth_blocks/revocation.cc */
  kLocRevocationDeriveSecretsFailedInDerive = 700,
  /* ./auth_blocks/revocation.cc */
  kLocRevocationCheckCredentialFailedInDerive = 701,
  /* ./auth_blocks/revocation.cc */
  kLocRevocationHkdfFailedInDerive = 702,
  /* ./auth_blocks/revocation.cc */
  kLocRevocationNoLeLabelInRevoke = 703,
  /* ./auth_blocks/revocation.cc */
  kLocRevocationRemoveCredentialFailedInRevoke = 704,
  /* ./auth_session.cc */
  kLocAuthSessionRemoveFailedInRemoveKeysetByLabel = 705,
  /* ./auth_blocks/fp_service.cc */
  kLocFpServiceVerifyCouldNotGetFpManager = 706,
  /* ./auth_blocks/fp_service.cc */
  kLocFpServiceCheckResultFailedYesRetry = 707,
  /* ./auth_blocks/fp_service.cc */
  kLocFpServiceCheckResultFailedNoRetry = 708,
  /* =Obsolete= */
  kLocAuthBlockUtilUnknownUnsupportedInVerifyWithAuthFactor = 709,
  /* ./auth_session.cc */
  kLocAuthSessionPrepareWebAuthnSecretNoFileSystemKeyset = 710,
  /* ./auth_session.cc */
  kLocAuthSessionPrepareWebAuthnSecretNoUserSession = 711,
  /* ./auth_blocks/fp_service.cc */
  kLocFpServiceStartSessionFailure = 712,
  /* ./auth_blocks/fp_service.cc */
  kLocFpServiceCheckResultNoAuthSession = 713,
  /* ./auth_blocks/fp_service.cc */
  kLocFpServiceStartScanCouldNotGetFpManager = 714,
  /* =Obsolete= */
  kLocFpServiceStartScanNoStart = 715,
  /* =Obsolete= */
  kLocFpServiceStartScanLockedOut = 716,
  /* ./auth_blocks/fp_service.cc */
  kLocFpServiceStartConcurrentSession = 717,
  /* =Obsolete= */
  kLocFpServiceScanCouldNotGetFpManager = 718,
  /* =Obsolete= */
  kLocAuthBlockUtilUnimplementedPrepareForAdd = 719,
  /* ./userdataauth.cc */
  kLocUserDataAuthFactorExtendedInfoTypeFailure = 720,
  /* ./userdataauth.cc */
  kLocUserDataAuthFactorExtendedInfoRecoveryIdFailure = 721,
  /* ./userdataauth.cc */
  kLocUserDataAuthRecoveryObjectFailureGetRecoveryId = 722,
  /* =Obsolete= */
  kLocAuthBlockUtilNoTpmInGetAuthBlockWithType = 723,
  /* ./auth_blocks/auth_block_utility_impl.cc */
  kLocAuthBlockUtilEmptyListInGetAuthBlockWithType = 724,
  /* =Obsolete= */
  kGetDelayInSecondsFailedInPinDriverGetDelayInMilliseconds = 725,
  /* =Obsolete= */
  kGetDelayInSecondsFailedInPinDriverGetNextSignalDelayInSeconds = 726,
  /* ./flatbuffer_file.cc */
  kLocStoreFileFailedInFlatbufferFile = 727,
  /* ./flatbuffer_file.cc */
  kLocLoadFileFailedInFlatbufferFile = 728,
  //////////////////////////////////////////////////
  //// This is a separator block at value 1500
  //// See location_db.py for more info.
  //////////////////////////////////////////////////
  /* ./challenge_credentials/challenge_credentials_helper_impl.cc */
  kLocChalCredHelperROCAVulnerableInCheckSrkRocaStatus = 1500,
  /* ./challenge_credentials/challenge_credentials_helper_impl.cc */
  kLocChalCredHelperCantQueryROCAVulnInCheckSrkRocaStatus = 1501,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManInvalidLESecretInConvertTpmError = 1502,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManInvalidResetSecretInConvertTpmError = 1503,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManTooManyAttemptsInConvertTpmError = 1504,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManPCRNotMatchInConvertTpmError = 1505,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManHashTreeInConvertTpmError = 1506,
  /* ./auth_session.cc */
  kLocAuthSessionUserNotFoundInAuthAuthFactor = 1507,
  //////////////////////////////////////////////////
  //// This is a separator block at value 1700
  //// See location_db.py for more info.
  //////////////////////////////////////////////////
  //////////////////////////////////////////////////
  //// This is a separator block at value 1900
  //// See location_db.py for more info.
  //////////////////////////////////////////////////
  /* ./cryptorecovery/recovery_crypto_impl.cc */
  kLocRecoveryCryptoNoContextInDecryptResponse = 1900,
  /* ./cryptorecovery/recovery_crypto_impl.cc */
  kLocRecoveryCryptoResponseErrInDecryptResponse = 1901,
  /* ./cryptorecovery/recovery_crypto_impl.cc */
  kLocRecoveryCryptoBadPayloadInDecryptResponse = 1902,
  /* ./cryptorecovery/recovery_crypto_impl.cc */
  kLocRecoveryCryptoBadADInDecryptResponse = 1903,
  /* ./cryptorecovery/recovery_crypto_impl.cc */
  kLocRecoveryCryptoNoEpochKeyInDecryptResponse = 1904,
  /* ./cryptorecovery/recovery_crypto_impl.cc */
  kLocRecoveryCryptoBadEpochKeyInDecryptResponse = 1905,
  /* ./cryptorecovery/recovery_crypto_impl.cc */
  kLocRecoveryCryptoDHFailedInDecryptResponse = 1906,
  /* ./cryptorecovery/recovery_crypto_impl.cc */
  kLocRecoveryCryptoEncodePointFailedInDecryptResponse = 1907,
  /* ./cryptorecovery/recovery_crypto_impl.cc */
  kLocRecoveryCryptoECDHFailedInDecryptResponse = 1908,
  /* ./cryptorecovery/recovery_crypto_impl.cc */
  kLocRecoveryCryptoAESFailedInDecryptResponse = 1909,
  /* ./cryptorecovery/recovery_crypto_impl.cc */
  kLocRecoveryCryptoBadPlainTextInDecryptResponse = 1910,
  /* ./cryptorecovery/recovery_crypto_impl.cc */
  kLocRecoveryCryptoBadLedgerSignedProof = 1911,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockNoAuthInputInDerive = 1912,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockNoEpochResponseInDerive = 1913,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockNoEphPubKeyInDerive = 1914,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockNoRecoveryResponseInDerive = 1915,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockNoLedgerPubKeyInDerive = 1916,
  //////////////////////////////////////////////////
  //// This is a separator block at value 2100
  //// See location_db.py for more info.
  //////////////////////////////////////////////////
  /* ./auth_factor/verifiers/scrypt.cc */
  kLocScryptVerifierVerifyNoUserInput = 2100,
  /* ./auth_factor/verifiers/scrypt.cc */
  kLocScryptVerifierVerifyScryptFailed = 2101,
  /* ./auth_factor/verifiers/scrypt.cc */
  kLocScryptVerifierVerifyWrongScryptOutputSize = 2102,
  /* ./auth_factor/verifiers/scrypt.cc */
  kLocScryptVerifierVerifySecretMismatch = 2103,
  /* ./auth_blocks/generic.h */
  kLocGenericAuthBlockIsSupportedNotFound = 2104,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManPinWeaverFailedInGetDelaySchedule = 2105,
  /* ./auth_session.cc */
  kLocAuthSessionGetStoredFactorFailedInRecreate = 2106,
  /* =Obsolete= */
  kLocAuthSessionGetKeyDataFailedInRecreate = 2107,
  /* ./auth_factor/types/common.cc */
  kLocAuthFactorCommonPrepareForAddUnsupported = 2108,
  /* ./auth_factor/types/common.cc */
  kLocAuthFactorCommonPrepareForAuthUnsupported = 2109,
  /* ./auth_factor/types/fingerprint.cc */
  kLocAuthFactorFpPrepareForAddNoService = 2110,
  /* ./auth_factor/types/fingerprint.cc */
  kLocAuthFactorFpPrepareForAuthNoService = 2111,
  /* ./auth_factor/types/legacy_fingerprint.cc */
  kLocAuthFactorLegacyFpPrepareForAddUnsupported = 2112,
  /* ./auth_factor/types/common.cc */
  kLocAuthFactorCommonGetFactorDelayUnsupported = 2113,
  /* ./auth_factor/types/pin.cc */
  kLocAuthFactorPinGetFactorDelayWrongFactorType = 2114,
  /* ./auth_factor/types/pin.cc */
  kLocAuthFactorPinGetFactorDelayInvalidBlockState = 2115,
  /* ./auth_factor/types/pin.cc */
  kLocAuthFactorPinGetFactorDelayMissingLabel = 2116,
  /* ./auth_factor/types/pin.cc */
  kLocAuthFactorPinGetFactorDelayReadFailed = 2117,
  /* ./auth_session.cc */
  kLocAuthSessionSingleLabelFullAuthNotSupportedAuthAuthFactor = 2118,
  /* ./auth_session.cc */
  kLocAuthSessionMultiLabelFullAuthNotSupportedAuthAuthFactor = 2119,
  /* ./auth_session.cc */
  kLocAuthSessionVaultKeysetMissingInAuthViaVaultKey = 2120,
  //////////////////////////////////////////////////
  //// This is a separator block at value 2300
  //// See location_db.py for more info.
  //////////////////////////////////////////////////
  /* =Obsolete= */
  kLocAuthSessionManagerCreateFailed = 2300,
  /* =Obsolete= */
  kLocAuthSessionManagerTokenCollision = 2301,
  /* =Obsolete= */
  kLocAuthSessionCreateInitializedFail = 2302,
  /* ./auth_factor/verifiers/smart_card.cc */
  kLocSmartCardVerifierNoKeyService = 2303,
  /* ./auth_factor/verifiers/smart_card.cc */
  kLocSmartCardVerifierNoInputUser = 2304,
  /* ./auth_factor/verifiers/smart_card.cc */
  kLocSmartCardVerifierNoInputAuth = 2305,
  /* ./auth_factor/verifiers/smart_card.cc */
  kLocSmartCardVerifierNoInputAlg = 2306,
  /* ./auth_factor/verifiers/smart_card.cc */
  kLocSmartCardVerifierCannotVerify = 2307,
  /* ./challenge_credentials/challenge_credentials_helper_impl.cc */
  kLocChalCredHelperTpmUnavailableInCheckTpmStatus = 2308,
  /* ./auth_session_manager.cc */
  kLocAuthSessionManagerAuthSessionActive = 2309,
  /* ./auth_session_manager.cc */
  kLocAuthSessionManagerAuthSessionNotFound = 2310,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockCheckCredTPMLockedInDerive = 2311,
  /* ./userdataauth.cc */
  kLocUserDataAuthNoAuthSessionInCreateVaultKeyset = 2312,
  /* ./create_vault_keyset_rpc_impl.cc */
  kLocCreateVaultKeysetRpcImplUnauthedInCreateVaultKeyset = 2314,
  /* ./create_vault_keyset_rpc_impl.cc */
  kLocCreateVaultKeysetRpcImplyInvalidBlockType = 2315,
  /* ./create_vault_keyset_rpc_impl.cc */
  kLocCreateVaultKeysetRpcImplNullParamInCallbackInAddKeyset = 2316,
  /* ./create_vault_keyset_rpc_impl.cc */
  kLocCreateVaultKeysetRpcImplCreateFailedInAddKeyset = 2317,
  /* ./create_vault_keyset_rpc_impl.cc */
  kLocCreateVaultKeysetRpcImplAddVaultKeysetFailed = 2318,
  /* ./create_vault_keyset_rpc_impl.cc */
  kLocCreateVaultKeysetRpcImplClearKeyDataFromInitialKeysetFailed = 2320,
  /* ./create_vault_keyset_rpc_impl.cc */
  kLocCreateVaultKeysetRpcImplAddInitialFailedInAddKeyset = 2321,
  /* ./create_vault_keyset_rpc_impl.cc */
  kLocCreateVaultKeysetRpcImplNoVkInAddKeyset = 2322,
  /* ./create_vault_keyset_rpc_impl.cc */
  kLocCreateVaultKeysetRpcImplAddFailedInAddKeyset = 2323,
  //////////////////////////////////////////////////
  //// This is a separator block at value 2500
  //// See location_db.py for more info.
  //////////////////////////////////////////////////
  /* =Obsolete= */
  kLocAuthBlockUtilNullLeManagerInGetAuthBlockWithType = 2500,
  /* ./userdataauth.cc */
  kLocUserDataAuthNonEphemeralAuthSessionInPrepareEphemeralVault = 2501,
  /* ./userdataauth.cc */
  kLocUserDataAuthEphemeralAuthSessionAttemptPreparePersistentVault = 2502,
  /* ./userdataauth.cc */
  kLocUserDataAuthEphemeralAuthSessionAttemptCreatePersistentUser = 2503,
  /* ./auth_session.cc */
  kLocUpdateAuthInputNoWrappedSeedInVaultKeyset = 2504,
  /* ./auth_session.cc */
  kLocUpdateAuthInputResetSeedEmptyInVaultKeyset = 2505,
  /* ./auth_session.cc */
  kLocNoVkInAuthInputForMigration = 2506,
  /* ./keyset_management.cc */
  kLocKeysetManagementFailedRemoveInRemoveKeysetFile = 2507,
  /* ./auth_session.cc */
  kLocAuthSessionRemoveFailedInCleanUpAllBackupKeysets = 2508,
  /* ./auth_session.cc */
  kLocAuthSessionCleanupBackupFailedInAddauthFactor = 2509,
  /* ./auth_session.cc */
  kLocAuthSessionClobberResetSecretFailedInAddSecretToUSS = 2510,
  //////////////////////////////////////////////////
  //// This is a separator block at value 2700
  //// See location_db.py for more info.
  //////////////////////////////////////////////////
  /* ./userdataauth.cc */
  kLocUserDataAuthUserDirExistsInCreatePersistentUser = 2700,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockHwsecReadyErrorInIsSupported = 2701,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockHwsecNotReadyInIsSupported = 2702,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockCannotUnsealWithUserAuthInIsSupported = 2703,
  /* ./auth_blocks/tpm_bound_to_pcr_auth_block.cc */
  kLocTpmBoundToPcrAuthBlockNoKeyLoaderInIsSupported = 2704,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockHwsecReadyErrorInIsSupported = 2705,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockHwsecNotReadyInIsSupported = 2706,
  /* ./auth_blocks/tpm_not_bound_to_pcr_auth_block.cc */
  kLocTpmNotBoundToPcrAuthBlockNoKeyLoaderInIsSupported = 2707,
  /* ./auth_blocks/challenge_credential_auth_block.cc */
  kLocChalCredAuthBlockHwsecReadyErrorInIsSupported = 2708,
  /* ./auth_blocks/challenge_credential_auth_block.cc */
  kLocChalCredAuthBlockHwsecNotReadyInIsSupported = 2709,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockHwsecReadyErrorInIsSupported = 2710,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockHwsecNotReadyInIsSupported = 2711,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockCannotUnsealWithUserAuthInIsSupported = 2712,
  /* ./auth_blocks/tpm_ecc_auth_block.cc */
  kLocTpmEccAuthBlockNoKeyLoaderInIsSupported = 2713,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockHwsecReadyErrorInIsSupported = 2714,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockHwsecNotReadyInIsSupported = 2715,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocRecoveryAuthBlockHwsecNoCryptoInIsSupported = 2716,
  /* ./auth_blocks/auth_block_utility_impl.cc */
  kLocAuthBlockUtilNoSupportedInGetAuthBlockWithType = 2717,
  /* =Obsolete= */
  kLocAuthBlockUtilMaxValueUnsupportedInIsAuthBlockSupported = 2718,
  /* ./auth_blocks/auth_block_utility_impl.cc */
  kLocAuthBlockUtilNotSupportedInGetAuthBlockWithType = 2719,
  /* =Obsolete= */
  kLocAuthBlockUtilNotSupportedInGetAsyncAuthBlockWithType = 2720,
  /* ./auth_blocks/double_wrapped_compat_auth_block.cc */
  kLocDoubleWrappedAuthBlockTpmBlockErrorInIsSupported = 2721,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockHwsecReadyErrorInIsSupported = 2722,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockHwsecNotReadyInIsSupported = 2723,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockPinWeaverCheckFailInIsSupported = 2724,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockNoPinWeaverInIsSupported = 2725,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockNullLeManagerInIsSupported = 2726,
  /* =Obsolete= */
  kLocPinWeaverAuthBlockNoKeyLoaderInIsSupported = 2727,
  /* ./auth_session.cc */
  kLocAuthSessionNoVkInAddKeyset = 2728,
  /* ./auth_factor/auth_factor_manager.cc */
  kLocAuthFactorManagerEmptyReadInLoad = 2729,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSEmptySerializedInGetContainerFromFB = 2730,
  /* =Obsolete= */
  kLocAuthSessionDeleteOldBackupFailedInUpdateWithUSS = 2731,
  /* ./auth_session.cc */
  kLocAuthSessionRemoveFailedInCleanUpBackupKeyset = 2732,
  /* =Obsolete= */
  kLocAuthSessionNoBackupFlagInCleanUpBackupKeyset = 2733,
  //////////////////////////////////////////////////
  //// This is a separator block at value 2900
  //// See location_db.py for more info.
  //////////////////////////////////////////////////
  //////////////////////////////////////////////////
  //// This is a separator block at value 3100
  //// See location_db.py for more info.
  //////////////////////////////////////////////////
  //////////////////////////////////////////////////
  //// This is a separator block at value 3300
  //// See location_db.py for more info.
  //////////////////////////////////////////////////
  /* ./auth_blocks/biometrics_auth_block_service.cc */
  kLocBiometricsServiceStartEnrollConcurrentSession = 3300,
  /* ./auth_blocks/biometrics_auth_block_service.cc */
  kLocBiometricsServiceCreateCredentialNoSession = 3301,
  /* ./auth_blocks/biometrics_auth_block_service.cc */
  kLocBiometricsServiceStartSessionFailure = 3302,
  /* ./auth_blocks/biometrics_auth_block_service.cc */
  kLocBiometricsServiceCheckStartConcurrentSession = 3303,
  /* ./auth_blocks/biometrics_auth_block_service.cc */
  kLocBiometricsServiceStartSessionNoToken = 3304,
  /* ./auth_blocks/biometrics_auth_block_service.cc */
  kLocBiometricsServiceStartAuthenticateConcurrentSession = 3305,
  /* ./auth_blocks/biometrics_auth_block_service.cc */
  kLocBiometricsServiceMatchCredentialNoSession = 3306,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorCreateEcFailedInGenKey = 3307,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorNullCreatedKeyInGenKey = 3308,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorCreateEcFailedInGetKey = 3309,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorCreateBigNumsFailedInGetKey = 3310,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorGetCoordsFailedInGetKey = 3311,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorPointToBlobFailedInGetKey = 3312,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorCreateEcFailedInGetPoint = 3313,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorNullCreatedPointInGetPoint = 3314,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorKeyToBigNumFailedInGetPoint = 3315,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorSetCoordsFailedInGetPoint = 3316,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorCreateEcFailedInDecryptSecret = 3317,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorComputeSharedPointFailedInDecryptSecret = 3318,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorComputeSharedSecretFailedInDecryptSecret = 3319,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorDecryptFailedInDecryptSecret = 3320,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorParseKeyFailedInDerive = 3321,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorDecryptSecretFailedInDerive = 3322,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorCreateCredentialWrongSession = 3323,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorCreateCredentialBiodInternalError = 3324,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorMatchCredentialWrongSession = 3325,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorMatchCredentialNoRecords = 3326,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorMatchCredentialBiodInternalError = 3327,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorMatchCredentialNoMatch = 3328,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorCreateCredentialKeygenFailed = 3329,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorCreateCredentialGetKeyFailed = 3330,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorMatchCredentialKeygenFailed = 3331,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorMatchCredentialGetKeyFailed = 3332,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorCreateCredentialBiodNoResp = 3333,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorCreateCredentialDeriveSecretsFailed = 3334,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorMatchCredentialBiodNoResp = 3335,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorMatchCredentialDeriveSecretsFailed = 3336,
  /* =Obsolete= */
  kLocFingerprintAuthBlockUnimplemented = 3337,
  /* =Obsolete= */
  kLocFingerprintAuthBlockPrepareForRemovalUnimplemented = 3338,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockNoServiceInIsSupported = 3339,
  /* =Obsolete= */
  kLocAuthBlockUtilFingerprintNoServiceInGetAsyncAuthBlock = 3340,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockHwsecReadyErrorInIsSupported = 3341,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockHwsecNotReadyInIsSupported = 3342,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockPinWeaverCheckFailInIsSupported = 3343,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockPinWeaverNotEnabledInIsSupported = 3344,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockNullLeManagerInIsSupported = 3345,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockNoUsernameInCreate = 3346,
  /* =Obsolete= */
  kLocFingerprintAuthBlockNoRateLimiterInCreate = 3347,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockNoResetSecretInCreate = 3348,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockNoNonceInCreate = 3349,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockStartBioAuthFailedInCreate = 3350,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockCreateCredentialFailedInCreate = 3351,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockCreateRateLimiterFailedInCreate = 3352,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockInsertCredentialFailedInCreate = 3353,
  /* ./auth_blocks/biometrics_command_processor_impl.cc */
  kLocBiometricsProcessorMatchCredentialUnexpectedScanResult = 3354,
  /* =Obsolete= */
  kLocAuthBlockUtilPrepareForAuthFingerprintNoService = 3355,
  /* =Obsolete= */
  kLocAuthBlockUtilPrepareForAddInvalidAuthFactorType = 3356,
  /* ./auth_session.cc */
  kLocRateLimiterNoResetSecretInAuthInputForAdd = 3357,
  /* ./auth_session.cc */
  kLocAuthSessionDeriveUSSSecretFailedInAddSecretToUSS = 3358,
  /* ./auth_session.cc */
  kLocNewRateLimiterWithNoSecretInAddSecretToUSS = 3359,
  /* ./auth_session.cc */
  kLocAddRateLimiterLabelFailedInAddSecretToUSS = 3360,
  /* ./auth_session.cc */
  kLocAddRateLimiterSecretFailedInAddSecretToUSS = 3361,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockNoUsernameInSelect = 3362,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockNoNonceInSelect = 3363,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockStartBioAuthFailedInSelect = 3364,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockAuthenticateCredentialFailedInSelect = 3365,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockFactorNotFoundInSelect = 3366,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockNoAuthSecretInDerive = 3367,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockNoAuthPinInDerive = 3368,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockWrongAuthBlockStateInDerive = 3369,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockNoGscSecretLabelInDerive = 3370,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockCheckCredentialFailedInCreate = 3371,
  /* ./auth_blocks/auth_block.h */
  kLocAuthBlockSelectFactorNotSupported = 3372,
  /* =Obsolete= */
  kLocAuthBlockSyncSelectFactorNotSupported = 3373,
  /* ./auth_blocks/auth_block_utility_impl.cc */
  kLocAuthBlockUtilNoAuthBlockInSelectAuthFactor = 3374,
  /* ./auth_session.cc */
  kLocAuthSessionUserNotFoundInMultiLabelAuthAuthFactor = 3375,
  /* ./auth_session.cc */
  kLocAuthSessionFactorNotFoundInMultiLabelAuthAuthFactor = 3376,
  /* ./auth_session.cc */
  kLocAuthSessionMultiLabelMismatchedAuthTypes = 3377,
  /* ./auth_session.cc */
  kLocAuthSessionInvalidBlockTypeInAuthAuthFactor = 3378,
  /* ./auth_session.cc */
  kLocAuthSessionMismatchedBlockTypesInAuthAuthFactor = 3379,
  /* ./auth_session.cc */
  kLocAuthSessionMultiLabelInvalidStorageType = 3380,
  /* ./auth_session.cc */
  kLocAuthSessionAuthInputParseFailed4InAuthAuthFactor = 3381,
  /* =Obsolete= */
  kLocAuthSessionLoadUSSFailedInAuthInputForSelect = 3382,
  /* ./auth_session.cc */
  kLocAuthSessionGetMetadataFailedInAuthInputForSelect = 3383,
  /* ./auth_session.cc */
  kLocAuthSessionNoRateLimiterInAuthInputForSelect = 3384,
  /* ./auth_session.cc */
  kLocAuthSessionNullParamInAuthViaSelected = 3385,
  /* ./auth_session.cc */
  kLocAuthSessionSelectionFailed = 3386,
  /* =Obsolete= */
  kLocAuthBlockUtilPrepareForAddFingerprintNoService = 3387,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockServiceNotReadyIsSupported = 3388,
  /* ./auth_blocks/fingerprint_auth_block.cc */
  kLocFingerprintAuthBlockAuthenticateCredentialLockedInSelect = 3389,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManUnSyncedTreeInRemoveCred = 3390,
  /* ./le_credential_manager_impl.cc */
  kLocLECredManExpiredInConvertTpmError = 3391,
  /* ./auth_factor/types/fingerprint.cc */
  kLocAuthFactorFingerprintGetFactorDelayWrongFactorType = 3392,
  /* ./auth_factor/types/fingerprint.cc */
  kLocAuthFactorFingerprintGetFactorDelayNoUserMetadataReader = 3393,
  /* ./auth_factor/types/fingerprint.cc */
  kLocAuthFactorFingerprintGetFactorDelayLoadMetadataFailed = 3394,
  /* ./auth_factor/types/fingerprint.cc */
  kLocAuthFactorFingerprintGetFactorDelayNoLabel = 3395,
  /* ./auth_factor/types/fingerprint.cc */
  kLocAuthFactorFingerprintGetFactorDelayReadFailed = 3396,
  /* ./auth_factor/types/common.cc */
  kLocAuthFactorCommonIsExpiredUnsupported = 3397,
  /* ./auth_factor/types/fingerprint.cc */
  kLocAuthFactorFingerprintIsExpiredWrongFactorType = 3398,
  /* ./auth_factor/types/fingerprint.cc */
  kLocAuthFactorFingerprintIsExpiredNoUserMetadataReader = 3399,
  /* ./auth_factor/types/fingerprint.cc */
  kLocAuthFactorFingerprintIsExpiredLoadMetadataFailed = 3400,
  /* ./auth_factor/types/fingerprint.cc */
  kLocAuthFactorFingerprintIsExpiredNoLabel = 3401,
  /* ./auth_factor/types/fingerprint.cc */
  kLocAuthFactorFingerprintIsExpiredReadFailed = 3402,
  //////////////////////////////////////////////////
  //// This is a separator block at value 3500
  //// See location_db.py for more info.
  //////////////////////////////////////////////////
  /* =Obsolete= */
  kLocAuthBlockUtilPrepareInvalidAuthFactorType = 3500,
  /* ./auth_session.cc */
  kLocAuthSessionInvalidAuthFactorTypeInPrepareAuthFactor = 3501,
  /* ./auth_session.cc */
  kLocAuthSessionInvalidPurposeInPrepareAuthFactor = 3502,
  /* ./auth_session.cc */
  kLocAuthSessionPrepareBadAuthFactorType = 3503,
  /* =Obsolete= */
  kLocPinWeaverAuthBlockFailedToGetStateFailedInPrepareForRemoval = 3504,
  /* =Obsolete= */
  kLocPinWeaverAuthBlockNoLabelInPrepareForRemoval = 3505,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocCryptohomeRecoveryAuthBlockNoRecoveryIdInCreate = 3506,
  /* ./auth_blocks/cryptohome_recovery_auth_block.cc */
  kLocCryptohomeRecoveryAuthBlockFailedRecoveryIdReadInCreate = 3507,
  /* =Obsolete= */
  kLocAuthSessionUpdateKeysetFailedInUpdateWithUSS = 3508,
  /* ./userdataauth.cc */
  kLocUserDataAuthPrepareAuthFactorAuthSessionNotFound = 3509,
  /* ./userdataauth.cc */
  kLocUserDataAuthTerminateAuthFactorAuthSessionNotFound = 3510,
  /* ./auth_session.cc */
  kLocAuthSessionInvalidAuthFactorTypeInTerminateAuthFactor = 3511,
  /* ./auth_session.cc */
  kLocAuthSessionTerminateBadAuthFactorType = 3512,
  /* ./auth_session.cc */
  kLocAuthSessionTerminateInactiveAuthFactor = 3513,
  /* ./auth_blocks/fp_service.cc */
  kLocFpServiceCheckSessionStartCouldNotGetFpManager = 3514,
  /* =Obsolete= */
  kLocAuthBlockUtilUnimplementedPrepareForAuthFingerprint = 3515,
  /* ./auth_session.cc */
  kLocAuthSessionMismatchedZeroLabelSizeAuthAuthFactor = 3516,
  /* ./auth_session.cc */
  kLocAuthSessionVerifierNotValidInAuthAuthFactor = 3517,
  /* ./auth_session.cc */
  kLocAuthSessionAuthInputParseFailedInAuthAuthFactor = 3518,
  /* ./auth_session.cc */
  kLocAuthSessionMismatchedSingleLabelSizeAuthAuthFactor = 3519,
  /* ./auth_session.cc */
  kLocAuthSessionAuthInputParseFailed2InAuthAuthFactor = 3520,
  /* ./auth_session.cc */
  kLocAuthSessionAuthInputParseFailed3InAuthAuthFactor = 3521,
  /* ./auth_session.cc */
  kLocAuthSessionMismatchedMultipLabelSizeAuthAuthFactor = 3522,
  /* =Obsolete= */
  kLocAuthSessionLabelLookupUnimplemented = 3523,
  /* ./userdataauth.cc */
  kLocUserDataMalformedRequestInAuthAuthFactor = 3524,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSDeserializeFailedInGeUserMetadata = 3525,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSGetUserMetadataFailedInFromEncContainer = 3526,
  /* ./user_secret_stash/user_secret_stash.cc */
  kLocUSSGetUserMetadataFailedInFromEncContainerWrappingKey = 3527,
  /* =Obsolete= */
  kLocFingerprintAuthBlockFailedToGetStateFailedInPrepareForRemoval = 3528,
  /* =Obsolete= */
  kLocFingerprintAuthBlockNoTemplateIdInPrepareForRemoval = 3529,
  /* =Obsolete= */
  kLocFingerprintAuthBlockNoLabelInPrepareForRemoval = 3530,
  /* ./userdataauth.cc */
  kLocUserDataAuthNoAuthSessionInUpdateAuthFactorMetadata = 3531,
  /* =Obsolete= */
  kLocUserDataAuthNoAuthFactorInUpdateAuthFactorMetadata = 3532,
  /* ./userdataauth.cc */
  kLocUserDataAuthProtoFailureInReplyWithAuthFactorStatus = 3533,
  /* ./auth_session.cc */
  kLocAuthSessionNoLabelInUpdateAuthFactorMetadata = 3534,
  /* ./auth_session.cc */
  kLocAuthSessionFactorNotFoundInUpdateAuthFactorMetadata = 3535,
  /* ./auth_session.cc */
  kLocAuthSessionUnknownFactorInUpdateAuthFactorMetadata = 3536,
  /* ./auth_session.cc */
  kLocAuthSessionDifferentLabelInUpdateAuthFactorMetadata = 3537,
  /* ./auth_session.cc */
  kLocAuthSessionDifferentTypeInUpdateAuthFactorMetadata = 3538,
  /* =Obsolete= */
  kLocAuthSessionBadMetadataUpdateAuthFactorMetadata = 3539,
  /* ./auth_session.cc */
  kLocAuthSessionFailedSaveInUpdateAuthFactorMetadata = 3540,
  /* ./auth_session.cc */
  kLocAuthSessionNameTooLongInUpdateAuthFactorMetadata = 3541,
  /* ./auth_blocks/pin_weaver_auth_block.cc */
  kLocPinWeaverAuthBlockRemoveCredential = 3542,
  // End of generated content.
};
// The enum value should not exceed 65535, otherwise we need to adjust the way
// Unified Error Code is allocated in cryptohome/error/cryptohome_tpm_error.h
// and libhwsec/error/tpm_error.h so that “Cryptohome.Error.LeafErrorWithTPM”
// UMA will continue to work.

}  // namespace error

}  // namespace cryptohome

#endif  // CRYPTOHOME_ERROR_LOCATIONS_H_
