#!/bin/bash

# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

IMAGE_DIR="/home/.shadow"
USERID="$(cat "${IMAGE_DIR}/salt" <(echo -n "$1") | openssl sha1)"

echo "Data belonging to $1 is stored in ${IMAGE_DIR}/${USERID}"
