// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef VM_TOOLS_CROS_IM_BACKEND_TEXT_INPUT_ENUMS_H_
#define VM_TOOLS_CROS_IM_BACKEND_TEXT_INPUT_ENUMS_H_

// Enum definitions from the text-input protocols. These should remain in sync
// with the definitions generated from text-input-extension-unstable-v1.xml and
// text-input-unstable-v1.xml in the respective client-protocol.h files.

// Having these enums separated from the generated Wayland headers allows
// frontends to not need a dependency on the Wayland headers, which the backend
// otherwise abstracts away.

// TODO(timloh): Add some sort of checks to ensure these are kept in sync.

#ifndef ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_ENUM
#define ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_ENUM
enum zwp_text_input_v1_preedit_style {
  ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_DEFAULT = 0,
  ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_NONE = 1,
  ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_ACTIVE = 2,
  ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_INACTIVE = 3,
  ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_HIGHLIGHT = 4,
  ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_UNDERLINE = 5,
  ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_SELECTION = 6,
  ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_INCORRECT = 7,
};
#endif  // ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_ENUM

#ifndef ZWP_TEXT_INPUT_V1_CONTENT_HINT_ENUM
#define ZWP_TEXT_INPUT_V1_CONTENT_HINT_ENUM
enum zwp_text_input_v1_content_hint {
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_NONE = 0x0,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_DEFAULT = 0x7,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_PASSWORD = 0xc0,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_AUTO_COMPLETION = 0x1,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_AUTO_CORRECTION = 0x2,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_AUTO_CAPITALIZATION = 0x4,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_LOWERCASE = 0x8,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_UPPERCASE = 0x10,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_TITLECASE = 0x20,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_HIDDEN_TEXT = 0x40,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_SENSITIVE_DATA = 0x80,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_LATIN = 0x100,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_MULTILINE = 0x200,
};
#endif /* ZWP_TEXT_INPUT_V1_CONTENT_HINT_ENUM */

#ifndef ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_ENUM
#define ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_ENUM
enum zwp_text_input_v1_content_purpose {
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_NORMAL = 0,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_ALPHA = 1,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_DIGITS = 2,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_NUMBER = 3,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_PHONE = 4,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_URL = 5,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_EMAIL = 6,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_NAME = 7,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_PASSWORD = 8,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_DATE = 9,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_TIME = 10,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_DATETIME = 11,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_TERMINAL = 12,
};
#endif /* ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_ENUM */

#ifndef ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_ENUM
#define ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_ENUM
enum zcr_extended_text_input_v1_input_type {
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_NONE = 0,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_TEXT = 1,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_PASSWORD = 2,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_SEARCH = 3,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_EMAIL = 4,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_NUMBER = 5,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_TELEPHONE = 6,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_URL = 7,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_DATE = 8,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_DATE_TIME = 9,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_DATE_TIME_LOCAL = 10,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_MONTH = 11,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_TIME = 12,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_WEEK = 13,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_TEXT_AREA = 14,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_CONTENT_EDITABLE = 15,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_DATE_TIME_FIELD = 16,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_NULL = 17,
};
#endif /* ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_TYPE_ENUM */

#ifndef ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_MODE_ENUM
#define ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_MODE_ENUM
enum zcr_extended_text_input_v1_input_mode {
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_MODE_DEFAULT = 0,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_MODE_NONE = 1,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_MODE_TEXT = 2,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_MODE_TEL = 3,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_MODE_URL = 4,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_MODE_EMAIL = 5,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_MODE_NUMERIC = 6,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_MODE_DECIMAL = 7,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_MODE_SEARCH = 8,
};
#endif /* ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_MODE_ENUM */

#ifndef ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_FLAGS_ENUM
#define ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_FLAGS_ENUM
enum zcr_extended_text_input_v1_input_flags {
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_FLAGS_NONE = 0,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_FLAGS_AUTOCOMPLETE_ON = 1 << 0,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_FLAGS_AUTOCOMPLETE_OFF = 1 << 1,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_FLAGS_AUTOCORRECT_ON = 1 << 2,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_FLAGS_AUTOCORRECT_OFF = 1 << 3,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_FLAGS_SPELLCHECK_ON = 1 << 4,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_FLAGS_SPELLCHECK_OFF = 1 << 5,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_FLAGS_AUTOCAPITALIZE_NONE = 1 << 6,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_FLAGS_AUTOCAPITALIZE_CHARACTERS = 1 << 7,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_FLAGS_AUTOCAPITALIZE_WORDS = 1 << 8,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_FLAGS_AUTOCAPITALIZE_SENTENCES = 1 << 9,
  ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_FLAGS_HAS_BEEN_PASSWORD = 1 << 10,
};
#endif /* ZCR_EXTENDED_TEXT_INPUT_V1_INPUT_FLAGS_ENUM */

#ifndef ZCR_EXTENDED_TEXT_INPUT_V1_LEARNING_MODE_ENUM
#define ZCR_EXTENDED_TEXT_INPUT_V1_LEARNING_MODE_ENUM
enum zcr_extended_text_input_v1_learning_mode {
  ZCR_EXTENDED_TEXT_INPUT_V1_LEARNING_MODE_DISABLED = 0,
  ZCR_EXTENDED_TEXT_INPUT_V1_LEARNING_MODE_ENABLED = 1,
};
#endif /* ZCR_EXTENDED_TEXT_INPUT_V1_LEARNING_MODE_ENUM */

#ifndef ZCR_EXTENDED_TEXT_INPUT_V1_INLINE_COMPOSITION_SUPPORT_ENUM
#define ZCR_EXTENDED_TEXT_INPUT_V1_INLINE_COMPOSITION_SUPPORT_ENUM
enum zcr_extended_text_input_v1_inline_composition_support {
  ZCR_EXTENDED_TEXT_INPUT_V1_INLINE_COMPOSITION_SUPPORT_UNSUPPORTED = 0,
  ZCR_EXTENDED_TEXT_INPUT_V1_INLINE_COMPOSITION_SUPPORT_SUPPORTED = 1,
};
#endif /* ZCR_EXTENDED_TEXT_INPUT_V1_INLINE_COMPOSITION_SUPPORT_ENUM */

#ifndef ZCR_EXTENDED_TEXT_INPUT_V1_SURROUNDING_TEXT_SUPPORT_ENUM
#define ZCR_EXTENDED_TEXT_INPUT_V1_SURROUNDING_TEXT_SUPPORT_ENUM
enum zcr_extended_text_input_v1_surrounding_text_support {
  ZCR_EXTENDED_TEXT_INPUT_V1_SURROUNDING_TEXT_SUPPORT_UNSUPPORTED = 0,
  ZCR_EXTENDED_TEXT_INPUT_V1_SURROUNDING_TEXT_SUPPORT_SUPPORTED = 1,
};
#endif /* ZCR_EXTENDED_TEXT_INPUT_V1_SURROUNDING_TEXT_SUPPORT_ENUM */

#endif  // VM_TOOLS_CROS_IM_BACKEND_TEXT_INPUT_ENUMS_H_
