#!/bin/sh

# Copyright 2012 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# File to store firmware timing information
BIOS_TIMES_FILE="/var/log/bios_times.txt"

if ! /usr/bin/cbmem > ${BIOS_TIMES_FILE} 2> /dev/null; then
  echo "unavailable" > ${BIOS_TIMES_FILE}
fi

