#! /bin/sh

# Copyright 2010 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# This script prints the family name, style, and version for the fonts

AWK_PROG='
  BEGIN {
    FS = ":"
  }
  {
    sub(",.*", "", $2); # remove style translations (eg, Fett is Bold in German)
    sub(".*=", "", $3); # strip version to just the number
    printf("%s, %s, version=%.3f\n", $1, $2, $3/65536.0);
  } 
'

fc-list : family style fontversion | awk "$AWK_PROG" | sort -f


