#!/bin/bash
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

sudo sed -i \
  's#^PATH=.*$#PATH="/mnt/host/source/chromite/sdk/bin:/mnt/host/source/chromite/bin"#' \
  /etc/env.d/99chromiumos
sudo env-update
