#!/bin/bash

# Copyright 2009 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

mkdir -p "${ROOT_FS_DIR}/usr/share/power_manager"
echo 1 > "${ROOT_FS_DIR}/usr/share/power_manager/disable_idle_suspend"
