#!/bin/bash
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Forcibly replace <dev-libs/openssl-1.1.1u-r2 with >=dev-libs/openssl-1.1.1-r2
# and openssl-3. `-r2` introduced the `PITA` slot for openssl-1.1.1u.
set -u

equery --quiet l '=dev-libs/openssl-1*:0'
exit_code="$?"
case "${exit_code}" in
  0 )
    # Purge old packages.
    sudo emerge --rage-clean \
      '<=dev-libs/openssl-1.1.1u-r2' \
      'dev-lang/python:3.6'
    # Force update for packages that use openssl-3.
    exec sudo emerge -j2 -gu --verbose-conflicts \
      app-admin/sudo \
      '=dev-libs/openssl-1*:PITA' \
      '=dev-libs/openssl-3*:0' \
      dev-vcs/git \
      net-libs/nghttp2 \
      net-misc/curl
    ;;

  # `equery` will exit with 3 if it completed successfully but found no matches.
  3 )
    exit 0
    ;;

  * )
    exit "${exit_code}"
    ;;
esac
