#!/bin/bash
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Ancient pre-`cros_gdb --board` support installed symlinks here. Let's get
# everyone on the same page.
sudo rm -rf /usr/lib/debug/build
