#!/bin/bash
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Force clean up some SDK packages that have been removed.
pkgs=(
  dev-lang/python:3.6
  dev-python/aiocontextvars
  dev-python/contextvars
  dev-python/dataclasses
)
sudo emerge --rage -q "${pkgs[@]}"
