#!/bin/bash
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Re-install gentoolkit: it may have been removed by clean-outdated-pkgs, and is
# required for eclean in update_chroot (b/305259495).

sudo emerge --newuse -qgu app-portage/gentoolkit
