#!/bin/bash
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Everything should be using /run/lock, not /var/lock.
sudo rm -rf /var/lock
