#!/bin/bash
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Workaround parallel cros_setup_toolchains race.
# b/299321780
set -x
sudo emerge -gu -j4 virtual/pkgconfig virtual/yacc
